#!/bin/sh

#Group ID: V-39262
#Group Title: SRG-OS-000078
#Version: SRG-OS-000078-ESXI5
#Severity: medium
#Description: The use of longer passwords reduces the ability of attackers to successfully obtain valid passwords using guessing or exhaustive search techniques by increasing the password search space.
#Rule Title: The system must require that passwords contain a minimum of 14 characters.
#Version: SRG-OS-000078-ESXI5

#Check Content: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell and Options, respectively. Start the ESXi Shell service, where/as required.
#As root, log in to the host and verify the expected settings are configured in the  /etc/pam.d/passwd file. The entry format is :

#"password requisite /lib/security/pam_passwdqc.so similar=deny retry=N min=N0,N1,N2,N3,N4"

#In addition to other password characteristics, the "N4" field controls the minimum required length of 14 characters.

# grep "^password" /etc/pam.d/passwd | grep requisite | grep "min="

#If the "N4" password complexity field is not set to "14" or greater and the "N0" thru "N3" fields are not set to "disabled", this is a finding.


#Fix Text: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell and Options, respectively. Start the ESXi Shell service, where/as required.

#As root, log in to the host and ensure the expected settings of the "min" keyword are configured in the  /etc/pam.d/passwd file. 

# vi /etc/pam.d/passwd

#Set the "N4" password complexity field to "14" or greater and set  the "N0" thru "N3" fields to "disabled", i.e., min=disabled,disabled,disabled,disabled,14

#Re-enable Lockdown Mode on the host.

#Solved by V-39246 script above
