#!/bin/sh

#Group ID: V-39260
#Group Title: SRG-OS-000120
#Version: SRG-OS-000120-ESXI5
#Severity: medium
#Description: Systems must employ cryptographic hashes for passwords using the SHA-2 family of algorithms or FIPS 140-2 approved successors. The use of unapproved algorithms may result in weak password hashes more vulnerable to compromise.
#Rule Title: The password hashes stored on the system must have been generated using a FIPS 140-2 approved cryptographic hashing algorithm.
#Version: SRG-OS-000120-ESXI5

#Check Content: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell and Options, respectively. Start the ESXi Shell service, where/as required.
#As root, log in to the host and verify the expected setting is configured in the /etc/pam.d/passwd file. The entry format will look similar to "password sufficient /lib/security/$ISA/pam_unix.so use_authtok nullok shadow". Search for the existing hash key (sha512).

# grep "^password sufficient " /etc/pam.d/passwd | grep sha512

#If sha512 is missing from the configuration, this is a finding.

#Re-enable Lockdown Mode on the host.


#Fix Text: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell and Options, respectively. Start the ESXi Shell service, where/as required.
#As root, log in to the host and verify the expected setting is configured in the /etc/pam.d/passwd file. The entry format will look similar to "password sufficient /lib/security/$ISA/pam_unix.so use_authtok nullok shadow". Edit the file and replace the existing hash key ( md5, des, or sha256) with sha512 or append sha512, if there is no existing key. For example: "password sufficient /lib/security/$ISA/pam_unix.so use_authtok nullok shadow sha512".

#Re-enable Lockdown Mode on the host.
if grep "sufficient " /etc/pam.d/passwd | grep sha512; then
echo "SHA512 is chosen"
else
sed -e '/password   sufficient/s/$/ usha512/' -i /etc/pam.d/passwd
echo "SHA512 is now set in PAM"
fi