#!/bin/sh

#Group ID: V-39280
#Group Title: GEN005524
#Version: GEN005524-ESXI5-000104
#Severity: low
#Description: GSSAPI authentication is used to provide additional authentication mechanisms to applications. Allowing GSSAPI authentication through SSH exposes the system's GSSAPI to remote hosts, increasing the attack surface of the system. GSSAPI authentication must be disabled unless needed.
#Rule Title: The SSH daemon must not permit GSSAPI authentication unless needed.
#Version: GEN005524-ESXI5-000104

#Check Content: Disable lock down mode. Enable the ESXi Shell. Check the SSH daemon configuration for the GSSAPIAuthentication setting. 
# grep -i GSSAPIAuthentication /etc/ssh/sshd_config | grep -v '^#' 
#Edit the SSH daemon configuration and add/modify the "GSSAPIAuthentication" configuration and set it to "no".

if grep -i GSSAPIAuthentication /etc/ssh/sshd_config | grep no; then
echo "GSSAPIAuthentication is turned off"
elif grep -i GSSAPIAuthentication /etc/ssh/sshd_config | grep yes;then
sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
echo "GSSAPIAuthentication has been turned off"
else
echo "GSSAPIAuthentication no" >> /etc/ssh/sshd_config
echo "Added 'GSSAPIAuthentication no' to sshd_config"
fi
