#!/bin/sh

#Group ID: V-39252
#Group Title: SRG-OS-000248
#Version: SRG-OS-000248-ESXI5
#Severity: high
#Description: The .rhosts or hosts.equiv files are used to configure host-based authentication for individual users or the system. Host-based authentication is not sufficient for preventing unauthorized access to the system. 
#Rule Title: There must be no .rhosts  or hosts.equiv files on the system.
#Version: SRG-OS-000248-ESXI5

#Check Content: The files hosts.equiv (/etc) and .rhosts (in the user home directory) contains host/user pairs to be trusted by the local system.  

#Locate the files:
# ls -l /etc/hosts.equiv
# find / | grep .rhosts
#or
# cd <user's home directory> 
# ls -l .rhosts

#If the hosts.equiv file or one or more .rhosts files are found, this is a finding.


#Fix Text: Remove the file(s):
# rm -f /etc/hosts.equiv
# rm -f <user's home directory>/.rhosts

if find / | grep .rhosts; then
echo "SRG-OS-000248 has to be fixed manually" >> /tmp/sysadmintodo
else
echo "No rhosts found."
fi