#!/bin/sh

#Group ID: V-39409
#Group Title: SRG-OS-000215
#Version: SRG-OS-000215-ESXI5
#Severity: medium
#Description: Remote logging to a central log host provides a secure, centralized store for ESXi logs. By gathering host log files onto a central host it can more easily monitor all hosts with a single tool. It can also do aggregate analysis and searching to look for such things as coordinated attacks on multiple hosts. Logging to a secure, centralized log server also helps prevent log tampering and also provides a long-term audit record.
#Rule Title: The operating system must back up audit records on an organization-defined frequency onto a different system or media than the system being audited.
#Version: SRG-OS-000215-ESXI5

#Check Content: Verify the vSphere Syslog Collector syslog host has been configured. From the vSphere Client:  Select the host and click "Configuration >> Advanced Settings >> Syslog >> Global". Verify the 'Syslog.global.logHost' is set to the (site-specific) syslog server hostname.

#If the 'Syslog.global.logHost' is unconfigured, this is a finding.


#Fix Text: Step 1:  Verify the vSphere Syslog Collector syslog host has been configured. If not, install/enable the vSphere Syslog Collector.
#Step 2:  From the vSphere Client:  Select the host and click "Configuration >> Advanced Settings >> Syslog >> Global".  
#Step 3: Set 'Syslog.global.logHost' to the syslog server hostname.
echo "Fixed by V-39408" >> /tmp/sysadmintodo