#!/bin/sh

#Group ID: V-39414
#Group Title: GEN005501
#Version: GEN005501-ESXI5-9778
#Severity: medium
#Description: SSHv1 is not a DoD-approved protocol and has many well-known vulnerability exploits. Exploits of the SSH client could provide access to the system with the privileges of the user running the client.
#Rule Title: The SSH client must be configured to only use the SSHv2 protocol.
#Version: GEN005501-ESXI5-9778
#Check the SSH client configuration for required protocol. # grep -i "Protocol 2" /etc/ssh/ssh_config | grep -v '^#' 
#If no lines are returned, or the returned protocol list contains anything except 2, this is a finding.
#Edit the SSH client  configuration and add/modify the "Protocol" configuration for Protocol 2 only. 

if grep -i "Protocol 2" /etc/ssh/ssh_config | grep -v '^#' 
echo "sshd is set to only use Protocol 2"
else
echo "Protocol 2" >> /etc/ssh/ssh_config
fi
if grep -i "Protocol 2,1" /etc/ssh/ssh_config then;
sed -i 's@Protocol 2,1@Protocol 2@g' /etc/ssh/ssh_config
fi
