#!/bin/sh

#Group ID: V-39402
#Group Title: SRG-OS-000157
#Version: SRG-OS-000157-ESXI5
#Severity: medium
#Description: The Cipher-Block Chaining (CBC) mode of encryption as implemented in the SSHv2 protocol is vulnerable to chosen plain text attacks and must not be used. 
#Rule Title: The SSH client must be configured to not use CBC-based ciphers.
#Version: SRG-OS-000157-ESXI5
#Check Content: Disable lock down mode.
#Enable the ESXi Shell.
# Check the SSH client configuration for allowed ciphers. # grep -i ciphers /etc/ssh/ssh_config | grep -v '^#' 
# If no lines are returned, or the returned ciphers list contains any cipher ending with cbc, this is a finding.
#Fix Text: Disable lock down mode.
#Enable the ESXi Shell.

#Edit the SSH client configuration and add/modify the "Ciphers" configuration (examples of Disallowed ciphers:  aes128-cbc, aes192-cbc, aes256-cbc, arcfour256blowfish-cbc, cast128-cbc, 3des-cbc).

if grep -i cbc /etc/ssh/ssh_config; then
       
sed -i 's/aes128-cbc//g' /etc/ssh/sshd_config
        echo "aes128-cbc has been removed in sshd_config"
sed -i 's/aes192-cbc//g' /etc/ssh/sshd_config
        echo "aes192-cbc has been removed in sshd_config"

sed -i 's/aaes256-cbc//g' /etc/ssh/sshd_config
        echo "aes256-cbc has been removed in sshd_config"

sed -i 's/arcfour256blowfish-cbc//g' /etc/ssh/sshd_config
        echo "arcfour256blowfish-cbc has been removed in sshd_config"

sed -i 's/cast128-cbc//g' /etc/ssh/sshd_config
        echo "cast128-cbc has been removed in sshd_config"

sed -i 's/3des-cbc//g' /etc/ssh/sshd_config
        echo "3des-cbc has been removed in sshd_config"
echo "Ciphers have been fixed"
else
echo "Ciphers are good"
fi
