#!/bin/sh

#Group ID: V-39427
#Group Title: GEN001375
#Version: GEN001375-ESXI5-000086
#Severity: low
#Description: To provide availability for name resolution services, multiple redundant name servers are mandated. A failure in name resolution could lead to the failure of security functions requiring name resolution, which may include time synchronization, centralized authentication, and remote system logging.
#Rule Title: For systems using DNS resolution, at least two name servers must be configured.
#Version: GEN001375-ESXI5-000086
#If DNS is not configured and is not used, this is not a finding.
#If DNS is configured with less than 2 servers, this is a finding.
#If DNS is configured has less than 2 servers configured, add a second server.

if grep -c "nameserver" /etc/resolv.conf|grep "2"; then
echo "nameservers are setup correctly"
else

if grep -i "HostIPAddr" /etc/vmware/esx.conf |grep -q "205."; then
sed -i 's@nameserver@#nameserver@g' /etc/resolv.conf
echo "nameserver 205.110.86.2" >> /etc/resolv.conf
echo "nameserver 205.110.86.3" >> /etc/resolv.conf
echo "Set to KC nameservers"
else
sed -i 's@nameserver@#nameserver@g' /etc/resolv.conf
echo "192.156.28.170" >> /etc/resolv.conf
echo "192.156.28.171" >> /etc/resolv.conf
echo "Set to Indy nameservers"
echo "Fixed"
fi
fi