#!/bin/sh

#Group ID: V-39349
#Group Title: SRG-OS-99999-ESXI5
#Version: SRG-OS-99999-ESXI5-000155
#Severity: low
#Description: When adding ESXi hosts to Active Directory, if the group "ESX Admins" exists, all user/group accounts assigned to the group will have full administrative access to the host. Discretion should be used when managing membership to the "ESX Admins" group.
#Rule Title: Active Directory ESX Admin group membership must be verified unused.
#Version: SRG-OS-99999-ESXI5-000155

#Check Content: For systems that do not use Active Directory and have no local user accounts, other than root and/or vpxuser, this check is not applicable.

#For systems that do not use Active Directory and do have local user accounts, other than root and/or vpxuser, this check is a finding.

#From the vSphere Client/vCenter, select the host, then Configuration >> Software/Advanced Settings >> HostAgent.

#Verify "Config.HostAgent.plugins.hostsvc.esxAdminsGroup" is not set to "ESX Admins".

#If the "Config.HostAgent.plugins.hostsvc.esxAdminsGroup" keyword is set to "ESX Admins", this is a finding.


#Fix Text: From the vSphere Client/vCenter, select the host, then Configuration >> Software/Advanced Settings >> HostAgent.

#Change the "Config.HostAgent.plugins.hostsvc.esxAdminsGroup" to a pre-defined group other than the default "ESX Admins".

#Note: The new administrator group must have been previously defined on the Active Directory server.

echo "Servers do not use AD" >> /tmp/sysadmintodo
echo "Servers do not use AD"