#!/bin/sh

#Group ID: V-39373
#Group Title: ESXI5-VMNET
#Version: ESXI5-VMNET-000016
#Severity: high
#Description: If the virtual machine operating system changes the MAC address, it can send frames with an impersonated source MAC address at any time. This allows it to stage malicious attacks on the devices in a network by impersonating a network adaptor authorized by the receiving network. This will prevent VMs from changing their effective MAC address. It will affect applications that require this functionality. An example of an application like this is Microsoft Clustering, which requires systems to effectively share a MAC address. This will also affect how a layer 2 bridge will operate. This will also affect applications that require a specific MAC address for licensing. VMs, guest OSs, and/or applications that require specific MAC settings must be placed in a separate, specially-configured  Portgroup on the vSwitch.
#Rule Title: The system must ensure the virtual switch MAC Address Change policy is set to reject.
#Version: ESXI5-VMNET-000016

#Check Content: From the vSphere Client, connect to the vCenter Server and as administrator: 
#Go to "Home>> Inventory>> Hosts and clusters". Select each ESXi host with active virtual switches connected to active VMs requiring securing. Go to tab "Configuration>> Network>> vSwitch(?)>> Properties>> Ports>> vSwitch>> Default Policies>> Security". Verify the "Mac Address Changes" = "Reject".

#If the VM/guest OS/application requires a specific MAC Address parameter setting for normal operation and is placed in a separate, specially-configured Portgroup ( with "Mac Address Changes" = "Accept") on the vSwitch, this is not a finding.

#If the VM/guest OS/application does not require a specific MAC Address parameter setting for normal operation and the "Mac Address Changes" parameter is not set to "Reject", this is a finding.


#Fix Text: From the vSphere Client, connect to the vCenter Server and as administrator: 
#Go to "Home>> Inventory>> Hosts and clusters". Select each ESXi host with active virtual switches connected to active VMs requiring securing. Go to tab "Configuration>> Network>> vSwitch(?)>> Properties>> Ports>> vSwitch>> Default Policies>> Security". Change the "Mac Address Changes" = "Reject".

if grep 'macChange = "true"' /etc/vmware/esx.conf; then
echo "macChange is set to true, need to change to false"
sed -i 's@macChange = "true"@macChange = "false"@g' /etc/vmware/esx.conf
else
echo 'macChange = false, your good"
fi