#!/bin/sh

#Group ID: V-39426
#Group Title: GEN002460
#Version: GEN002460-ESXI5-20047
#Severity: medium
#Description: Files with the setgid bit set will allow anyone running these files to be temporarily assigned the GID of the file. While many system files depend on these attributes for proper operation, security problems can result if setgid is assigned to programs that allow reading and writing of files, or shell escapes.
#Rule Title: The system must be checked weekly for unauthorized setgid files, as well as, unauthorized modification to authorized setgid files.
#Version: GEN002460-ESXI5-20047
#Check Content: Ask the SA if the system is checked for unauthorized setgid files on a weekly basis. If no automated or manual process is in place, this is a finding.
#Fix Text: Configure the system to check for unauthorized setgid files on a weekly basis.
#if find / -xdev \( -perm -4000 -o -perm -2000 \) -type f -print |grep -v "busybox"|grep -v "vmx"; then
#echo "Found"

#else 
#echo "Nothing Found"
#fi


# After finding the files, I have no idea what to do, cause busybox and the vmx files should stay sticky.
echo "GEN002460-ESXI5-20047 has to be done manually" >> /tmp/sysadmintodo
echo 'find / -xdev \( -perm -4000 -o -perm -2000 \) -type f -print |grep -v "busybox"|grep -v "vmx"' >> /tmp/sysadmintodo
echo "Above command will find what needs to be fixed." >> /tmp/sysadmintodo
