#!/bin/sh

#Group ID: V-39370
#Group Title: ESXI5-VMNET
#Version: ESXI5-VMNET-000013
#Severity: medium
#Description: If the virtual machine operating system changes the MAC address, the operating system can send frames with an impersonated source MAC address at any time. This allows an operating system to stage malicious attacks on the devices in a network by impersonating a network adaptor authorized by the receiving network. Forged transmissions should be set to accept by default. This means the virtual switch does not compare the source and effective MAC addresses. To protect against MAC address impersonation, all virtual switches should have forged transmissions set to reject.
#Rule Title: The system must ensure that the virtual switch Forged Transmits policy is set to reject.
#Version: ESXI5-VMNET-000013

#Check Content: The "Forged Transmits" parameter must be set to "Reject" on all vSwitches.

#From the vSphere Client/vCenter as administrator, verify by using the vSphere Client to connect to the vCenter Server and as administrator: 1. Go to "Home > Inventory > Hosts and clusters". 2. Select each ESXi host with active virtual switches connected to active VM's requiring securing. 3. Go to tab "Configuration > Network > vSwitch(?) > Properties > Ports > vSwitch > Default Policies > Security" 4. "Forged Transmits" = "Reject"

#If the "Forged Transmits" parameter is not set to "Reject" on all vSwitches, this is a finding.


#Fix Text: The "Forged Transmits" parameter must be set to "Reject" on all vSwitches.

#From the vSphere Client/vCenter as administrator, using the vSphere Client to connect to the vCenter Server and as administrator: 1. Go to "Home > Inventory > Hosts and clusters". 2. Select each ESXi host with active virtual switches connected to active VM's requiring securing. 3. Go to tab "Configuration > Network > vSwitch(?) > Properties > Ports > vSwitch > Default Policies > Security" 4. Set "Forged Transmits" = "Reject".
echo "Fixed by V-39371" >> /tmp/sysadmintodo