#!/bin/sh

#Group ID: V-39382
#Group Title: GEN000945
#Version: GEN000945-ESXI5-000333
#Severity: medium
#Description: The library search path environment variable(s) contain a list of directories for the dynamic linker to search to find libraries. If this path includes the current working directory or other relative paths, libraries in these directories may be loaded instead of system libraries. This variable is formatted as a colon-separated list of directories. If there is an empty entry, such as a leading or trailing colon or two consecutive colons, this is interpreted as the current working directory. Entries starting with a slash (/) are absolute paths.
#Rule Title: The root accounts library search path must be the system default and must contain only absolute paths.
#Version: GEN000945-ESXI5-000333

#Check Content: Disable lock down mode.
#Enable the ESXi Shell.
#<file> = /etc/vmware/config
#<required_keyword> = libdir
#<required_keyword_setpoint> = /usr/lib/vmware
#Execute the following command(s):
# grep libdir /etc/vmware/config
#If the "libdir" path is not set to "/usr/lib/vmware", this is a finding.
#<required_keyword_setpoint> = /usr/lib/vmware
#Execute the following command(s):
#Set the "libdir" path to "/usr/lib/vmware".
#Re-enable lock down mode.

if grep -i 'libdir = "/usr/lib/vmware"' /etc/vmware/config; then
echo "libdir is setup"
else
sed -i 's/libdir =/#libdir =/g' /etc/vmware/config
echo 'libdir = "/usr/lib/vmware"' >> /etc/vmware/config
echo 'libdir = "/usr/lib/vmware" has been added to /etc/vmware/config"
fi