#!/bin/sh
#Group ID: V-39347
#Group Title: SRG-OS-99999-ESXI5
#Version: SRG-OS-99999-ESXI5-000152
#Severity: medium
#Description: ESXi hosts come with SSH which can be enabled to allow remote access without requiring user authentication. To enable password free access copy the remote users public key into the "/etc/ssh/keys-root/authorized_keys" file on the ESXi host. The presence of the remote user's public key in the "authorized_keys" file identifies the user as trusted, meaning the user is granted access to the host without providing a password. Note:  Lockdown mode does not apply to root users who log in using authorized keys. When you use an authorized key file for root user authentication, root users are not prevented from accessing a host with SSH even when the host is in lockdown mode.
#Rule Title: Keys from SSH authorized_keys file must be removed.
#Version: SRG-OS-99999-ESXI5-000152
#Check Content: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client.
#As root, log in to the host and verify the /etc/ssh/keys-root/authorized_keys file does not exist or is empty (zero bytes): 
# ls -l /etc/ssh/keys-root/authorized_keys
#If the authorized_keys file exists and is not empty, this is a finding.

if ls -l /etc/ssh/keys-root/authorized_keys |grep 0; then
echo "Either the authorized keys is being used, or is not installed"
else
echo "authorized_keys file exists and is not empty, this is a finding"
rm /etc/ssh/keys-root/authorized_keys
fi
