#!/bin/sh

#Group ID: V-39417
#Group Title: SRG-OS-99999-ESXI5
#Version: SRG-OS-99999-ESXI5-000144
#Severity: medium
#Description: If SNMP is not being used, it must remain disabled. If it is being used, the proper trap destination must be configured. If SNMP is not properly configured, monitoring information can be sent to a malicious host that can then use this information to plan an attack. SNMP must be configured on each ESXi host using Power/v CLI. vSphere PowerCLI is a command line tool used to automate vSphere management. PowerCLI is distributed as a Windows PowerShell snapin, and includes 300+ PowerShell cmdlets and use documentation.

#Rule Title: The system must ensure proper SNMP configuration.
#Version: SRG-OS-99999-ESXI5-000144

#Check Content: From the Power/v CLI, run:
#"vicfg-snmp.pl --server <server_name> -s" to determine if SNMP is being used. An alternative command option instead of the "-s" is "--show".

#If SNMP is not being used and "enabled" = 1, this is a finding. If the read-only community name is set to "public", this is a finding. If the read-write community name is set to private, this is a finding.


#Fix Text: If SNMP is not being used, configure "enabled" = 0. From the Power/v CLI, execute "vicfg-snmp.pl --server <server_name> -D".

#If SNMP is being used, ensure the community name is configured:
#From the vSphere CLI, type "vicfg-snmp.pl --server hostname --username <username> --password <password> -c <community_name>".

#To enable SNMP from the vSphere CLI, type. 
# vicfg-snmp.pl --server <hostname> --username <username> --password <password> --enable
echo "SRG-OS-99999-ESXI5-000144 has to be done manually" >> /tmp/sysadmintodo