#!/bin/sh

#Group ID: V-39274
#Group Title: GEN000380
#Version: GEN000380-ESXI5-000043
#Severity: low
#Description: If a user is assigned the GID of a group not existing on the system, and a group with that GID is subsequently created, the user may have unintended rights to that group.
#Rule Title: The GID assigned to a user must exist.
#Version: GEN000380-ESXI5-000043

#Check Content: From the vSphere Client/vCenter, click on the "Local Users and Groups" tab, then select to view Groups.  Select to view Users. Highlight the user, right click and select Edit. Click Cancel.

#If any user's primary GID is not found in the Group list, this is a finding.


#Fix Text: From the vSphere Client/vCenter, click on the "Local Users and Groups" tab, then select Groups. Highlight the user, right click the user and select Edit. Select/highlight/assign the user's correct primary GID. Click OK.
#
# Lock down creation of groups?
echo "GEN000380-ESXI5-000043 has to be done manually" >> /tmp/sysadmintodo