#!/bin/sh

#Group ID: V-39246
#Group Title: GEN000790
#Version: GEN000790-ESXI5-000085
#Severity: medium
#Description: An easily guessable password provides an open door to any external or internal malicious intruder. Many computer compromises occur as the result of account name and password guessing. This is generally done by someone with an automated script using repeated logon attempts until the correct account and password pair is guessed. Utilities, such as cracklib, can be used to validate passwords are not dictionary words and meet other criteria during password changes.
#Rule Title: The system must prevent the use of dictionary words for passwords.
#Version: GEN000790-ESXI5-000085

#Check Content: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell and Options, respectively. Start the ESXi Shell service, where/as required.
#As root, log in to the host and verify the expected settings are configured in the  /etc/pam.d/passwd file. The entry format is :

#"password requisite /lib/security/pam_passwdqc.so similar=deny retry=N min=N0,N1,N2,N3,N4"

#The "N2" field controls the behavior enforcing "no dictionary words". This flag should be set to "disabled".

# grep "^password" /etc/pam.d/passwd | grep requisite | grep "min="

#If the "N2" password complexity field is not set to "disabled", this is a finding.

#Re-enable Lockdown Mode on the host.


#Fix Text: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell and Options, respectively. Start the ESXi Shell service, where/as required.

#As root, log in to the host and ensure the expected settings of the "min" keyword are configured in the  /etc/pam.d/passwd file. 

# vi /etc/pam.d/passwd

#Set the "N2" password complexity field to "disabled", i.e., min=disabled,disabled,disabled,disabled,14

#Re-enable Lockdown Mode on the host.


if grep "^password" /etc/pam.d/passwd | grep requisite | grep "min=8,8"; then
	sed -i 's/min=8,8,8,7,6/min=disabled,disabled,disabled,disabled,14/g' /etc/pam.d/passwd
	echo "pam.d/password has been fixed"
else
	echo "pam.d/password is correctly setup"
fi

