#!/bin/sh

#Group ID: V-39368
#Group Title: ESXI5-VMNET
#Version: ESXI5-VMNET-000011
#Severity: medium
#Description: When a port group is set to VLAN 4095, this activates VGT mode. In this mode, the vSwitch passes all network frames to the guest VM without modifying the VLAN tags, leaving it up to the guest to deal with them. VLAN 4095 should be used only if the guest has been specifically configured to manage VLAN tags itself. If VGT is enabled inappropriately, it might cause denial-of-service or allow a guest VM to interact with traffic on an unauthorized VLAN.
#Rule Title: All port groups must not be configured to VLAN 4095 except for Virtual Guest Tagging (VGT).
#Version: ESXI5-VMNET-000011
#Check Content: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell, and Options, respectively. Start the ESXi Shell service, where/as required.
#As root, log in to the ESXi Shell and run the following command.
# esxcli network vswitch standard portgroup list
#If the VGT value (4095) is set and the guest is not configured to handle VLAN tags, this is a finding.
#As root, log in to the ESXi Shell and run the command to set the value to something other than the VGT 4095 value.
#esxcli network vswitch standard portgroup set --portgroup-name=<name> --vlan-id=<non-default_id_number>


echo "ESXI5-VMNET-000011 has to be done manually" >> /tmp/sysadmintodo
echo "#As root, log in to the ESXi Shell and run the command to set the value to something other than the VGT 4095 value. ">> /tmp/sysadmintodo
echo "#esxcli network vswitch standard portgroup set --portgroup-name=<name> --vlan-id=<non-default_id_number>" >> /tmp/sysadmintodo