#!/bin/sh

#Group ID: V-39276
#Group Title: GEN002140
#Version: GEN002140-ESXI5-000046
#Severity: medium
#Description: The shells file lists approved default shells. It helps provide layered defense to the security approach by ensuring users cannot change their default shell to an unauthorized shell that may not be secure. By default, the shells file contains the only shell files in the ESXi file system, /bin/ash and /bin/sh. Users not granted shell access are assigned the shell /sbin/nologin.
#Rule Title: All shells referenced in /etc/passwd must be listed in the /etc/shells file, except any shells specified for the purpose of preventing logins.
#Version: GEN002140-ESXI5-000046

#Check Content: Disable lock down mode. Enable the ESXi Shell.
#<file> = /etc/shells

#Available shells for ESXi are "/bin/sh" and "/bin/ash".

#Execute the following command(s):
# ls -lL `cat /etc/shells`

#If /etc/shells does not exist, this is a finding.

#If /etc/shells exists and is empty, this is a finding.

#If /etc/shells exists and includes both the /bin/sh and /bin/ash shells, this is not a finding.

#Re-enable lock down mode.


#Fix Text: Disable lock down mode. 
#Enable the ESXi Shell.
#<file> = /etc/shells
#Available shells for ESXi are "/bin/sh" and "/bin/ash".

#Ensure both the above interactive shell(s) are listed in the /etc/shells file. If necessary, add them:
# vi /etc/shells

#Re-enable lock down mode.
if ls -lL `cat /etc/shells`| grep -v "/bin/sh"|grep -v "/bin/ash"; then
echo "We have a problem, extra shells are installed"
echo "We have a problem, extra shells are installed" >> /tmp/sysadmintodo
echo "GEN002140-ESXI5-000046" >> /tmp/sysadmintodo
else
echo "All set"
fi 

