#!/bin/sh

#Group ID: V-39304
#Group Title: SRG-OS-99999-ESXI5
#Version: SRG-OS-99999-ESXI5-000150
#Severity: low
#Description: SAN activity must be segregated via zoning and LUN masking. The potential for any SAN client to mount and access any SAN drive will result in disk resource contention and data corruption. Zoning and LUN masking must be used to isolate and protect SAN storage devices. Use of zoning must also take into account any host groups on the SAN device(s).
#Rule Title: SAN resources must be masked and zoned appropriately.
#Version: SRG-OS-99999-ESXI5-000150

#Check Content: Zoning and masking capabilities for each SAN switch and disk array are vendor specific. Ask the SA if a SAN device is used to support hosts. If a SAN device is deployed and zoning/masking is not used, this is a finding.

#If SAN devices are not used, this is not a finding.


#Fix Text: If SAN devices are used, a vendor-specific procedure must be developed and documented to mask/zone host LUNs.

echo "Has to be checked via vSphere"
echo "If SAN devices are used, a vendor-specific procedure must be developed and documented to mask/zone host LUNs." >> /var/log/hardened.log
