#!/bin/sh

#Group ID: V-39371
#Group Title: ESXI5-VMNET
#Version: ESXI5-VMNET-000014
#Severity: medium
#Description: If the virtual machine operating system changes the MAC address, the operating system can send frames with an impersonated source MAC address at any time. This allows an operating system to stage malicious attacks on the devices in a network by impersonating a network adaptor authorized by the receiving network. Forged transmissions should be set to accept by default. This means the virtual switch does not compare the source and effective MAC addresses. To protect against MAC address impersonation, all virtual switches should have forged transmissions set to reject.
#Rule Title: The system must ensure that the dvPortgroup Forged Transmits policy is set to reject.
#Version: ESXI5-VMNET-000014

#Check Content: The "Forged Transmits" parameter must be set to "Reject" on all dvPortgroups. From the vSphere Client/vCenter as administrator: 

#Go to "Home>> Inventory>> Networking". Select each dvPortgroup connected to VMs. Go to tab "Summary>> Edit Settings>> Policies>> Security". Verify "Forged Transmits" = "Reject".

#If the "Forged Transmits" parameter is not set to "Reject" on all dvPortgroups, this is a finding.


#Fix Text: The "Forged Transmits" parameter must be set to "Reject" on all dvPortgroups.

#From the vSphere Client/vCenter as administrator: 

#Go to "Home>> Inventory>> Networking". 
#Select each dvPortgroup connected to VMs. 
#Go to tab "Summary>> Edit Settings>> Policies>> Security". 
#Set "Forged Transmits" = "Reject".

if grep 'forgedTx = "true"' /etc/vmware/esx.conf; then
echo "Forged transmits is set to true, need to change to false"
sed -i 's@forgedTx = "true"@.forgedTx = "false"@g' /etc/vmware/esx.conf
else
echo 'forgedTx = false, your good"
fi