#!/bin/sh

#Group ID: V-39428
#Group Title: GEN008680
#Version: GEN008680-ESXI5-000056
#Severity: high
#Description: Storing the boot loader on removable media in an insecure location could allow a malicious user to modify the systems boot instructions or boot to an insecure operating system.
#Rule Title: If the system boots from removable media, it must be stored in a safe or similarly secured container.
#Version: GEN008680-ESXI5-000056

#Check Content: Ask the SA if the system boots from removable media. If so, ask if the boot media is stored in a secure container when not in use. If it is not, this is a finding.


#Fix Text: Store the system boot media in a secure container when not in use.
echo "GEN008680-ESXI5-000056 has to be done manually" >> /tmp/sysadmintodo