#!/bin/sh

#Group ID: V-39375
#Group Title: ESXI5-VMNET
#Version: ESXI5-VMNET-000018
#Severity: medium
#Description: When promiscuous mode is enabled for a virtual switch, all virtual machines connected to the dvPortgroup have the potential of reading all packets across that network, meaning only the virtual machines connected to that  dvPortgroup. Promiscuous mode is disabled by default on the ESXi Server.
#Rule Title: The system must ensure the virtual switch Promiscuous Mode policy is set to reject.
#Version: ESXI5-VMNET-000018

#Check Content: Use the vSphere Client to connect to the vCenter Server and as administrator: Go to "Home > Inventory > Hosts and clusters". Select each ESXi host with active virtual switches connected to active VM's requiring securing. Go to the tab "Configuration >> Network >> vSwitch(?) >> Properties >> Ports >> vSwitch >> Default Policies >> Security". Check that the "Promiscuous Mode" is set to "Reject". 

#If the "Promiscuous Mode" is not set to "Reject", this is a finding.

#
#Fix Text: From the vSphere Client/vCenter Server as administrator: Go to "Home>> Inventory>> Hosts and clusters". Select each ESXi host with active virtual switches connected to active VMs requiring securing. Go to tab "Configuration>> Network>> vSwitch(?)>> Properties>> Ports>> vSwitch>> Default Policies>> Security". Set "Promiscuous Mode" = "Reject".
echo "ESXI5-VMNET-000018 has to be done manually" >> /tmp/sysadmintodo