#!/bin/sh

#Group ID: V-39421
#Group Title: GEN005537
#Version: GEN005537-ESXI5-000111
#Severity: medium
#Description: SSH daemon privilege separation causes the SSH process to drop root privileges when not needed, which would decrease the impact of software vulnerabilities in the unprivileged section.
#Rule Title: The SSH daemon must use privilege separation.
#Version: GEN005537-ESXI5-000111
#Check Content: Disable lock down mode. Enable the ESXi Shell. Login as root and execute the following command(s):
# grep UsePrivilegeSeparation /etc/ssh/sshd_config
#If "UsePrivilegeSeparation" is set to "no" or the keyword/line is missing, this is a finding.
#Fix Text: Disable lock down mode. Enable the ESXi Shell. Login as root and execute the following command(s):
# vi /etc/ssh/sshd_config
#Add/modify the "UsePrivilegeSeparation " keyword to "yes", i.e.; UsePrivilegeSeparation=yes
if grep -i "UsePrivilegeSeparation"  /etc/ssh/sshd_config|grep '^#'; then
sed -i 's@#UsePrivilegeSeparation @UsePrivilegeSeparation @g' /etc/ssh/sshd_config
sed -i 's@UsePrivilegeSeparation no@UsePrivilegeSeparation yes@g' /etc/ssh/sshd_config
echo "UsePrivilegeSeparation on sshd"
else
echo "UsePrivilegeSeparation is setup already"
sed -i 's@UsePrivilegeSeparation no@UsePrivilegeSeparation yes@g' /etc/ssh/sshd_config
fi

if grep -i "UsePrivilegeSeparation" /etc/ssh/sshd_config; then
echo "UsePrivilegeSeparation is set"
else
echo "UsePrivilegeSeparation yes" >> /etc/ssh/sshd_config
fi