#!/bin/sh

#Group ID: V-39385
#Group Title: SRG-OS-000092
#Version: SRG-OS-000092-ESXI5
#Severity: medium
#Description: Enabling lockdown prevents all API-based access by the accounts to the ESXi host. Enabling lockdown mode disables all remote access to ESXi machines. 
#There are some operations, such as backup and troubleshooting that require direct access to the host. In these cases Lockdown Mode can be disabled on a temporary basis for specific hosts as needed, and then re-enabled when the task is completed. Lockdown restricts access to the ESXi console to the root user only, requiring non-root users access the host through vSphere Client/vCenter where RBAC and logging can be used to restrict and log activity. By forcing all interaction to occur through vCenter Server, the risk of someone inadvertently attaining elevated privileges or performing tasks that are not properly audited is greatly reduced. 
#Note:  Lockdown mode does not apply to root users who log in using authorized keys. When an authorized key file is used for root user authentication, root users are not prevented from accessing a host with SSH even when the host is in lockdown mode. Use of an authorized key file for root must therefore be disallowed.
#Rule Title: The system must enable lockdown mode to restrict remote access.
#Version: SRG-OS-000092-ESXI5
#Check Content: From the vSphere client, select the host then select "Configuration >> Security Profile". Verify Lockdown Mode is enabled.  
#Alternatively, issue the following command via the CLI:
# vim-cmd -U dcui vimsvc/auth/lockdown_is_enabled
#If Lockdown Mode is not enabled, this is a finding.
#Fix Text: To enable Lockdown mode, log in directly the ESXi host as root. Open the DCUI on the host. Press F2 for Initial Setup.
#Toggle the Configure Lockdown Mode setting and configure Lockdown Mode.
echo "SRG-OS-000092-ESXI5 has to be done manually" >> /tmp/sysadmintodo
echo "Realistically, if I re-enable lockdown mode, these scripts will fail."