#!/bin/sh

#Group ID: V-39346
#Group Title: SRG-OS-99999-ESXI5
#Version: SRG-OS-99999-ESXI5-000151
#Severity: low
#Description: If products that use the dvfilter network API are not used, the host should not be configured to send network information to a VM. If the API is enabled, an attacker might attempt to connect a VM to it, thereby potentially providing access to the network of other VMs on the host.

If a product uses this API, the host must be verified as being correctly configured.

#Rule Title: The system must prevent unintended use of dvfilter network APIs.
#Version: SRG-OS-99999-ESXI5-000151

#Check Content: From the vSphere client select the host and click "Configuration >> Advanced Settings >> Net" and verify the value of Net.DVFilterBindIpAddress. 

#For a host without a dvfilter-based network security appliance, the following kernel parameter value must be blank/empty: /Net/DVFilterBindIpAddress. 

#For a host with a dvfilter-based network security appliance is being used, the value of this parameter must be set to match the appliance.

#If a dvfilter-based network security appliance is not used and the kernel parameter /Net/DVFilterBindIpAddress is populated, this is a finding.

#If a dvfilter-based network security appliance is used and the kernel parameter /Net/DVFilterBindIpAddress does not match the appliance, this is a finding.


#Fix Text: From the vSphere client select the host and click "Configuration >> Advanced Settings >> Net" 
#Set the value of Net.DVFilterBindIpAddress to blank if a dvfilter-based network security appliance is not used or (where used) set the value of Net.DVFilterBindIpAddress to match the dvfilter-based network security appliance.

# I have no idea how to check for this automated

echo "SRG-OS-99999-ESXI5-000151 has to be done manually" >> /tmp/sysadmintodo