#!/bin/sh

#Group ID: V-39261
#Group Title: SRG-OS-000077
#Version: SRG-OS-000077-ESXI5
#Severity: medium
#Description: If a user, or root, used the same password continuously or was allowed to change it back shortly after being forced to change it to something else, it would provide a potential intruder with the opportunity to keep guessing at one user's password until it was guessed correctly.
#Rule Title: The system must prohibit the reuse of passwords within five iterations.
#Version: SRG-OS-000077-ESXI5

#Check Content: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell and Options, respectively. Start the ESXi Shell service, where/as required. "remember" is an option to pam_unix.so.

#As root, log in to the host and execute the following:
# grep "^password" /etc/pam.d/passwd | grep sufficient | grep "remember="

#If "remember" is set to less than 5, this is a finding.

#Re-enable Lockdown Mode on the host.


#Fix Text: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell and Options, respectively. Start the ESXi Shell service, where/as required. "remember" is an option to pam_unix.so. 
#As root, log in to the host and modify the "remember" keyword value, example: "remember=5".
# vi /etc/pam.d/passwd | grep sufficient | grep "remember="

#Re-enable Lockdown Mode on the host.

if grep "^password" /etc/pam.d/passwd | grep sufficient | grep "remember="; then
echo "PAM prohibits use of old passwords"
else
sed -e '/password   sufficient/s/$/ remember=5/' /etc/pam.d/passwd
echo "We have fixed PAM so that it doesn't use old passwords"
fi
