#!/bin/sh

#Group ID: V-39354
#Group Title: GEN005525
#Version: GEN005525-ESXI5-09994
#Severity: low
#Description: GSSAPI authentication is used to provide additional authentication mechanisms to applications. Allowing GSSAPI authentication through SSH exposes the system's GSSAPI to remote hosts, increasing the attack surface of the system. GSSAPI authentication must be disabled unless needed.
#Rule Title: The SSH client must not permit GSSAPI authentication unless needed.
#Version: GEN005525-ESXI5-09994
#Check Content: Disable lock down mode. Enable the ESXi Shell. Check the SSH client configuration for the GSSAPIAuthentication setting. 
# grep -i GSSAPIAuthentication /etc/ssh/ssh_config | grep -v '^#' 
#If "GSSAPIAuthentication" is set to "yes", this is a finding.'

if grep -i GSSAPIAuthentication /etc/ssh/ssh_config | grep no; then
echo "GSSAPIAuthentication is turned off"
elif grep -i GSSAPIAuthentication /etc/ssh/ssh_config | grep yes;then
sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/ssh_config
echo "GSSAPIAuthentication has been turned off"
else
echo "GSSAPIAuthentication no" >> /etc/ssh/ssh_config
echo "Added 'GSSAPIAuthentication no' to ssh_config"
fi
