#!/bin/sh

#Group ID: V-39390
#Group Title: SRG-OS-99999-ESXI5
#Version: SRG-OS-99999-ESXI5-000138
#Severity: medium
#Description: The ESXi Shell is an interactive command line interface (CLI) available at the ESXi server console. The ESXi shell provides temporary access to commands essential for server maintenance. Intended primarily for use in break-fix scenarios, the ESXi shell is well suited for checking and modifying configuration details, not always generally accessible, using the vSphere Client. The ESXi shell is accessible remotely using SSH. Under normal operating conditions, SSH access to the host must be disabled. As with the ESXi shell, SSH is also intended only for temporary use during break-fix scenarios. SSH must therefore be disabled under normal operating conditions and must only be enabled for diagnostics or troubleshooting. Remote access to the host must therefore be limited to the vSphere Client at all other times.
#Rule Title: The system must disable SSH.
#Version: SRG-OS-99999-ESXI5-000138

#Check Content: From the vSphere client, select the ESXi host, go to "Configuration >> Security Profile". In the "Services" section select "Properties".  Verify 'SSH' is stopped.

#If the SSH service is running, this is a finding. 

echo "SSH must stay on, can not comply with this request"
#Fix Text: From the vSphere client, select the ESXi host, go to "Configuration >> Security Profile". In the "Services" section select "Properties". Select "SSH", "Options..." and configure the 'SSH' option to "Start and stop manually".
#if /etc/init.d/SSH status|grep started; then
#echo "ssh is on"
#/etc/init.d/SSH stop
#else
#echo "ssh is off"
#fi