#!/bin/sh

#Group ID: V-39264
#Group Title: SRG-OS-000080
#Version: SRG-OS-000080-ESXI5
#Severity: medium
#Description: A system's BIOS or system controller handles the initial startup of a system and its configuration must be protected from unauthorized modification. When the BIOS or system controller supports the creation of user accounts or passwords, such protections must be used and accounts/passwords only assigned to system administrators. Failure to protect BIOS or system controller settings could result in Denial-of-Service or compromise of the system resulting from unauthorized configuration changes.
#Rule Title: System BIOS or system controllers supporting password protection must have administrator accounts/passwords configured, and no others.
#Version: SRG-OS-000080-ESXI5

#Check Content: On systems with a BIOS or system controller, ask the SA if a supervisor or administrator password is set. If a password is not set, this is a finding.


#Fix Text: On systems with a BIOS or system controller, set the supervisor or administrator password.

## HAS TO BE CHECKED MANUALLY
echo "SRG-OS-000080-ESXI5 has to be done manually" >> /tmp/sysadmintodo 