#!/bin/sh

#Group ID: V-39381
#Group Title: GEN002430
#Version: GEN002430-ESXI5
#Severity: medium
#Description: The "nodev" (or equivalent) mount option causes the system to not handle device files as system devices. This option must be used for mounting any file system that does not contain approved device files. Device files can provide direct access to system hardware and can compromise security if not protected.
#Rule Title: Removable media, remote file systems, and any file system that does not contain approved device files must be mounted with the nodev option.
#Version: GEN002430-ESXI5
#Check Content: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell and Options, respectively. Start the ESXi Shell service, where/as required. 
#As root, log in to the host.  Check the system for NFS mounts that do not use the nodev option. Execute the following:
#  cat /etc/fstab | grep -i nfs | grep -v "nodev"
#If the mounted NFS file systems do not use the nodev option, this is a finding.
#Fix Text: Temporarily disable Lockdown Mode and enable the ESXi Shell via the vSphere Client. Open the vSphere/VMware Infrastructure (VI) Client and log in with appropriate credentials. If connecting to vCenter Server, click on the desired host. Click the Configuration tab. Click Software, Security Profile, Services, Properties, ESXi Shell and Options, respectively. Start the ESXi Shell service, where/as required. As root, log in to the host.  Edit /etc/fstab and add the nodev option for all NFS file systems. Re-enable Lockdown Mode on the host.
#
echo "make backup of fstab"
cp fstab fstab.bak
if grep --silent -i nfs ./fstab| grep -i "nodev"; then
echo "NFS is secured"
else 
sed -e '/nfs/{/nodev/!s/\S\S*/&,nodev/4}' -e '/nfs/{/nosuid/!s/\S\S*/&,nosuid/4}' /etc/fstab.bak > /etc/fstab
echo "NFS has been secured"
fi