#!/bin/bash
# Created by Matthew M. Conley / SimonTek
# Feb. 10, 2015

#Group ID (Vulid): V-2228
#Group Title: WG400
#Rule ID: SV-6928r1_rule
#Severity: CAT II
#Rule Version (STIG-ID): WG400 A22
#Rule Title: All interactive programs (CGI) must be placed in a designated directory with appropriate permissions.
#Vulnerability Discussion: CGI scripts represents one of the most common and exploitable means of compromising a web server. By definition, CGI are executable by the operating system of the host server. While access control is provided via the web service, the execution of CGI programs is not otherwise limited unless the SA or Web Manager takes specific measures. CGI programs can access and alter data files, launch other programs and use the network. CGI programs can be written in any available programming language. C, PERL, PHP, Javascript, VBScript and shell (sh, ksh, bash) are popular choices.
#Responsibility: System Administrator
#IAControls: DCPA-1
#Check Content: 
#To preclude access to the servers root directory, ensure the following directive is in the httpd.conf file. This entry will also stop users from setting up .htaccess files which can override security features configured in httpd.conf.
# <DIRECTORY /[website root dir]>
# AllowOverride None
# </DIRECTORY>
#If the AllowOverride None is not set, this is a finding.
#Fix Text: Ensure the CGI (or equivalent i.e. scripts) directory has access controls IAW the WEB Services STIG.   



