#!/bin/bash
# RHEL-06-000194
# SV-50362r3_rule
if grep 'a always,exit -F arch=b32 -S lsetxattr -F auid>=500 -F auid!=4294967295' /etc/audit/audit.rules; then
echo "This machine is RHEL-06-000194 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000194 Compliant"
else
echo "This machine isn't RHEL-06-000194 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000194 Compliant"
echo '# RHEL-06-000194' >> /etc/audit/audit.rules
echo '-a always,exit -F arch=b32 -S lsetxattr -F auid>=500 -F auid!=4294967295 -k perm_mod' >> /etc/audit/audit.rules
echo '-a always,exit -F arch=b32 -S lsetxattr -F auid=0 -k perm_mod' >> /etc/audit/audit.rules
fi

if grep 'a always,exit -F arch=b64 -S lsetxattr -F auid>=500 -F auid!=4294967295' /etc/audit/audit.rules; then
echo "This machine is RHEL-06-000194 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000194 Compliant"
else
echo "This machine isn't RHEL-06-000194 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000194 Compliant"
echo '# RHEL-06-000194 64Bit' >> /etc/audit/audit.rules
echo '-a always,exit -F arch=b64 -S lsetxattr -F auid>=500 -F auid!=4294967295 -k perm_mod' >> /etc/audit/audit.rules
echo '-a always,exit -F arch=b64 -S lsetxattr -F auid=0 -k perm_mod' >> /etc/audit/audit.rules
/etc/init.d/auditd restart
fi

