#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38581
#Group Title: SRG-OS-999999
#Version: RHEL-06-000066
#Severity: medium
#Description: The "root" group is a highly-privileged group. Furthermore, the group-owner of this file should not have any access privileges anyway.
#Rule Title: The system boot loader configuration file(s) must be group-owned by root.
#Version: RHEL-06-000066

#Check Content: To check the group ownership of "/etc/grub.conf", run the command: 

#$ ls -lL /etc/grub.conf

#If properly configured, the output should indicate the following group-owner. "root" 
#If it does not, this is a finding.


#Fix Text: The file "/etc/grub.conf" should be group-owned by the "root" group to prevent destruction or modification of the file. To properly set the group owner of "/etc/grub.conf", run the command: 

# chgrp root /etc/grub.conf

if ls -lL /etc/grub.conf |grep " root "; then
echo "This machine is RHEL-06-000066 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000066 Compliant"
else
echo "This machine isn't RHEL-06-000066 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000066 Compliant"
chgrp root /etc/grub.conf
fi