#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38602
#Group Title: SRG-OS-000248
#Version: RHEL-06-000218
#Severity: high
#Description: The rlogin service uses unencrypted network communications, which means that data from the login session, including passwords and all other information transmitted during the session, can be stolen by eavesdroppers on the network.
#Rule Title: The rlogind service must not be running.
#Version: RHEL-06-000218

#Check Content: To check that the "rlogin" service is disabled in system boot configuration, run the following command: 

# chkconfig "rlogin" --list

#Output should indicate the "rlogin" service has either not been installed, or has been disabled at all runlevels, as shown in the example below: 

# chkconfig "rlogin" --list
#"rlogin" 0:off 1:off 2:off 3:off 4:off 5:off 6:off

#Run the following command to verify "rlogin" is disabled through current runtime configuration: 
# service rlogin status
#If the service is disabled the command will return the following output: 
#rlogin is stopped

#If the service is running, this is a finding.
#Fix Text: The "rlogin" service, which is available with the "rsh-server" package and runs as a service through xinetd, should be disabled. The "rlogin" service can be disabled with the following command: 



if chkconfig --list |grep rlogin|grep on; then
echo "This machine isn't RHEL-06-000218 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000218 Compliant"
chkconfig rlogin off
/etc/init.d/rlogin stop
else
echo "This machine is RHEL-06-000218 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000218 Compliant"
fi
