#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38548
#Group Title: SRG-OS-999999
#Version: RHEL-06-000099
#Severity: medium
#Description: An illicit ICMP redirect message could result in a man-in-the-middle attack.
#Rule Title: The system must ignore ICMPv6 redirects by default.
#Version: RHEL-06-000099

#Check Content: The status of the "net.ipv6.conf.default.accept_redirects" kernel parameter can be queried by running the following command: 

#$ sysctl net.ipv6.conf.default.accept_redirects

#The output of the command should indicate a value of "0". If this value is not the default value, investigate how it could have been adjusted at runtime, and verify it is not set improperly in "/etc/sysctl.conf". 
#If the correct value is not returned, this is a finding.


#Fix Text: To set the runtime status of the "net.ipv6.conf.default.accept_redirects" kernel parameter, run the following command: 

# sysctl -w net.ipv6.conf.default.accept_redirects=0

#If this is not the system's default value, add the following line to "/etc/sysctl.conf": 

#net.ipv6.conf.default.accept_redirects = 0

if grep ^net.ipv6.conf.default.accept_redirects /etc/sysctl.conf|grep 0; then
echo "This machine is RHEL-06-000099 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000099 Compliant"
else
echo "This machine isn't RHEL-06-000099 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000099 Compliant"
if grep --silent ^net.ipv6.conf.default.accept_redirects /etc/sysctl.conf ; then
	sed -i 's/^net.ipv6.conf.default.accept_redirects.*/net.ipv6.conf.default.accept_redirects = 0/g' /etc/sysctl.conf
else
	echo "" >> /etc/sysctl.conf
	echo "# Send ipv6 Redirects" >> /etc/sysctl.conf
	echo "net.ipv6.conf.default.accept_redirects = 0" >> /etc/sysctl.conf
fi
fi
