#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38512
#Group Title: SRG-OS-000146
#Version: RHEL-06-000117
#Severity: medium
#Description: The "iptables" service provides the system's host-based firewalling capability for IPv4 and ICMP.
#Rule Title: The operating system must prevent public IPv4 access into an organizations internal networks, except as appropriately mediated by managed interfaces employing boundary protection devices.
#Version: RHEL-06-000117

#Check Content: If the system is a cross-domain system, this is not applicable.
#Run the following command to determine the current status of the "iptables" service: 
# service iptables status
#If the service is enabled, it should return the following: 
#iptables is running...
#If the service is not running, this is a finding.

#Fix Text: The "iptables" service can be enabled with the following command: 

# chkconfig iptables on

if /etc/init.d/iptables |grep -iv "stop"; then
echo "This machine isn't RHEL-06-000117 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000117 Compliant"
chkconfig iptables on
/etc/init.d/iptables restart
else
echo "This machine is RHEL-06-000117 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000117 Compliant" 
fi  
