#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38672
#Group Title: SRG-OS-000096
#Version: RHEL-06-000289
#Severity: low
#Description: The "netconsole" service is not necessary unless there is a need to debug kernel panics, which is not common.
#Rule Title: The netconsole service must be disabled unless required.
#Version: RHEL-06-000289

#Check Content: To check that the "netconsole" service is disabled in system boot configuration, run the following command: 

# chkconfig "netconsole" --list
#Output should indicate the "netconsole" service has either not been installed, or has been disabled at all runlevels, as shown in the example below: 
# chkconfig "netconsole" --list
#"netconsole" 0:off 1:off 2:off 3:off 4:off 5:off 6:off
#Run the following command to verify "netconsole" is disabled through current runtime configuration: 
# service netconsole status
#If the service is disabled the command will return the following output: 
#netconsole is stopped
#If the service is running, this is a finding.
#Fix Text: The "netconsole" service is responsible for loading the netconsole kernel module, which logs kernel printk messages over UDP to a syslog server. This allows debugging of problems where disk logging fails and serial consoles are impractical. The "netconsole" service can be disabled with the following command: 
# chkconfig netconsole off

if chkconfig --list|grep netconsole |grep ":on "; then
echo "This machine isn't RHEL-06-000289 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000289 Compliant"
service netconsole stop
chkconfig netconsole off
else
echo "This machine is RHEL-06-000289 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000289 Compliant"
fi