#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38675
#Group Title: SRG-OS-999999
#Version: RHEL-06-000308
#Severity: low
#Description: A core dump includes a memory image taken at the time the operating system terminates an application. The memory image could contain sensitive data and is generally useful only for developers trying to debug problems.
#Rule Title: Process core dumps must be disabled unless needed.
#Version: RHEL-06-000308

#Check Content: To verify that core dumps are disabled for all users, run the following command: 

#$ grep core /etc/security/limits.conf

#The output should be: 
#* hard core 0

#If it is not, this is a finding.
#Fix Text: To disable core dumps for all users, add the following line to "/etc/security/limits.conf": 

#* hard core 0


if grep core /etc/security/limits.conf|grep -v '^#'|grep hard; then
echo "This machine is RHEL-06-000308 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000308 Compliant"
else
echo "This machine isn't RHEL-06-000308 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000308 Compliant"
echo "* hard core 0" >> /etc/security/limits.conf
fi