#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38627
#Group Title: SRG-OS-999999
#Version: RHEL-06-000256
#Severity: low
#Description: Unnecessary packages should not be installed to decrease the attack surface of the system.
#Rule Title: The openldap-servers package must not be installed unless required.
#Version: RHEL-06-000256

#Check Content: To verify the "openldap-servers" package is not installed, run the following command: 

#$ rpm -q openldap-servers
#The output should show the following. 
#package openldap-servers is not installed
#If it does not, this is a finding.
#Fix Text: The "openldap-servers" package should be removed if not in use. Is this machine the OpenLDAP server? If not, remove the package. 
# yum erase openldap-servers
#The openldap-servers RPM is not installed by default on RHEL6 machines. It is needed only by the OpenLDAP server, not by the clients which use LDAP for authentication. If the system is not intended for use as an LDAP Server it should be removed.

if rpm -q openldap-servers|grep "not installed"; then
echo "This machine is RHEL-06-000256 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000256 Compliant"
else
echo "This machine isn't RHEL-06-000256 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000256 Compliant"
yum erase openldap-servers -y
fi