#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38456
#Group Title: SRG-OS-999999
#Version: RHEL-06-000002
#Severity: low
#Description: Ensuring that "/var" is mounted on its own partition enables the setting of more restrictive mount options. This helps protect system services such as daemons or other programs which use it. It is not uncommon for the "/var" directory to contain world-writable directories, installed by other software packages.
#Rule Title: The system must use a separate file system for /var.
#Version: RHEL-06-000002

#Check Content: Run the following command to determine if "/var" is on its own partition or logical volume: 

#$ mount | grep "on /var "

#If "/var" has its own partition or volume group, a line will be returned. 
#If no line is returned, this is a finding.


#Fix Text: The "/var" directory is used by daemons and other system services to store frequently-changing data. Ensure that "/var" has its own partition or logical volume at installation time, or migrate it using LVM.
if mount | grep "on /var ";then
echo "All is set"
echo "This machine is RHEL-06-000002 Compliant" >> /var/log/Stig
else
echo "This machine isn't RHEL-06-000002 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000002 Compliant"
echo "This machine is RHEL-06-000002 Compliant" >> /var/log/Stig
fi
