#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38656
#Group Title: SRG-OS-999999
#Version: RHEL-06-000272
#Severity: low
#Description: Packet signing can prevent man-in-the-middle attacks which modify SMB packets in transit.
#Rule Title: The system must use SMB client signing for connecting to samba servers using smbclient.
#Version: RHEL-06-000272

#Check Content: To verify that Samba clients running smbclient must use packet signing, run the following command: 

# grep signing /etc/samba/smb.conf
#The output should show: 
#client signing = mandatory
#If it is not, this is a finding.
#Fix Text: To require samba clients running "smbclient" to use packet signing, add the following to the "[global]" section of the Samba configuration file in "/etc/samba/smb.conf": 
#client signing = mandatory
#Requiring samba clients such as "smbclient" to use packet signing ensures they can only communicate with servers that support packet signing.

if grep signing /etc/samba/smb.conf|grep "mandatory";then
echo "This machine is RHEL-06-000272 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000272 Compliant"
else
echo "This machine isn't RHEL-06-000272 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000272 Compliant"
sed -i '/global]/a \client signing = mandatory' /etc/samba/smb.conf
fi