#!/bin/bash
#Created by Matthew M. Conley / SimonTek
#Group ID: V-38439
#Group Title: SRG-OS-000001
#Version: RHEL-06-000524
#Severity: medium
#Description: A comprehensive account management process that includes automation helps to ensure the accounts designated as requiring attention are consistently and promptly addressed. Enterprise environments make user account management challenging and complex. A user management process requiring administrators to manually address account management functions adds risk of potential oversight.
#Rule Title: The system must provide automated support for account management functions.
#Version: RHEL-06-000524
#Check Content: Interview the SA to determine if there is an automated system for managing user accounts, preferably integrated with an existing enterprise user management system.
#If there is not, this is a finding.
#Fix Text: Implement an automated system for managing user accounts that minimizes the risk of errors, either intentional or deliberate.  If possible, this system should integrate with an existing enterprise user management system, such as, one based Active Directory or Kerberos.


echo "Must be done manually" 
echo "This machine isn't RHEL-06-000524 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000524 Compliant"



#if 
#echo "This machine is RHEL-06-000524 Compliant" >> /var/log/Stig
#echo "This machine is RHEL-06-000524 Compliant"
#else
#echo "This machine isn't RHEL-06-000524 Compliant" >> /var/log/Stig
#echo "This machine isn't RHEL-06-000524 Compliant"
#fi