#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38475
#Group Title: SRG-OS-000078
#Version: RHEL-06-000050
#Severity: medium
#Description: Requiring a minimum password length makes password cracking attacks more difficult by ensuring a larger search space. However, any security benefit from an onerous requirement must be carefully weighed against usability problems, support costs, or counterproductive behavior that may result.

#While it does not negate the password length requirement, it is preferable to migrate from a password-based authentication scheme to a stronger one based on PKI (public key infrastructure).
#Rule Title: The system must require passwords to contain a minimum of 14 characters.
#Version: RHEL-06-000050

#Check Content: To check the minimum password length, run the command: 

#$ grep PASS_MIN_LEN /etc/login.defs

#The DoD requirement is "14". 
#If it is not set to the required value, this is a finding.


#Fix Text: To specify password length requirements for new accounts, edit the file "/etc/login.defs" and add or correct the following lines: 

#PASS_MIN_LEN 14



#The DoD requirement is "14". If a program consults "/etc/login.defs" and also another PAM module (such as "pam_cracklib") during a password change operation, then the most restrictive must be satisfied.
if grep PASS_MIN_LEN /etc/login.defs|grep -v "14"; then
echo "This machine isn't RHEL-06-000050 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000050 Compliant"
var_accounts_password_minlen_login_defs="14"
grep -q ^PASS_MIN_LEN /etc/login.defs && \
  sed -i "s/PASS_MIN_LEN.*/PASS_MIN_LEN     $var_accounts_password_minlen_login_defs/g" /etc/login.defs
if ! [ $? -eq 0 ]; then
    echo "PASS_MIN_LEN      $var_accounts_password_minlen_login_defs" >> /etc/login.defs
fi
else
echo "This machine is RHEL-06-000050 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000050 Compliant"

fi

