#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38652
#Group Title: SRG-OS-999999
#Version: RHEL-06-000269
#Severity: medium
#Description: Legitimate device files should only exist in the /dev directory. NFS mounts should not present device files to users.
#Rule Title: Remote file systems must be mounted with the nodev option.
#Version: RHEL-06-000269

#Check Content: To verify the "nodev" option is configured for all NFS mounts, run the following command: 
#$ mount | grep nfs
#All NFS mounts should show the "nodev" setting in parentheses. 
#If the setting does not show, this is a finding.
#Fix Text: Add the "nodev" option to the fourth column of "/etc/fstab" for the line which controls mounting of any NFS mounts.

if mount | grep nfs|grep "nodev"; then
echo "This machine isn't RHEL-06-000269 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000269 Compliant"
cp /etc/fstab /etc/fstab.bak
sed -e '/nfs/{/nodev/!s/\S\S*/&,nodev/4}' -e '/nfs/{/nosuid/!s/\S\S*/&,nosuid/4}' /etc/fstab.bak > /etc/fstab
echo "NFS has been secured"
else
echo "This machine is RHEL-06-000269 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000269 Compliant"
fi
