#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38693
#Group Title: SRG-OS-999999
#Version: RHEL-06-000299
#Severity: low
#Description: Passwords with excessive repeating characters may be more vulnerable to password-guessing attacks.
#Rule Title: The system must require passwords to contain no more than three consecutive repeating characters.
#Version: RHEL-06-000299

#Check Content: To check the maximum value for consecutive repeating characters, run the following command: 
#$ grep pam_cracklib /etc/pam.d/system-auth
#Look for the value of the "maxrepeat" parameter. The DoD requirement is 3. 
#If maxrepeat is not found or not set to the required value, this is a finding.
#Fix Text: The pam_cracklib module's "maxrepeat" parameter controls requirements for consecutive repeating characters. Edit the "/etc/pam.d/system-auth" file to include the following line prior to the "password include system-auth-ac" line: 
#password required pam_cracklib.so maxrepeat=3

#maxrepeat=3

if grep pam_cracklib /etc/pam.d/system-auth|grep maxrepeat=3; then
echo "This machine is RHEL-06-000299 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000299 Compliant"
else
echo "This machine isn't RHEL-06-000299 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000299 Compliant"
sed -i '/^password    requisite/ s/$/ maxrepeat=3/' /etc/pam.d/system-auth
fi
