#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38687
#Group Title: SRG-OS-000160
#Version: RHEL-06-000321
#Severity: low
#Description: Providing the ability for remote users or systems to initiate a secure VPN connection protects information when it is transmitted over a wide area network.
#Rule Title: The system must provide VPN connectivity for communications over untrusted networks.
#Version: RHEL-06-000321

#Check Content: Run the following command to determine if the "openswan" package is installed: 
# rpm -q openswan
#If the package is not installed, this is a finding.
#Fix Text: The Openswan package provides an implementation of IPsec and IKE, which permits the creation of secure tunnels over untrusted networks. The "openswan" package can be installed with the following command: 
# yum install openswan

if rpm -q openswan; then
echo "This machine is RHEL-06-000321 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000321 Compliant"
else
echo "This machine isn't RHEL-06-000321 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000321 Compliant"
yum install openswan -y
fi