#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38480
#Group Title: SRG-OS-999999
#Version: RHEL-06-000054
#Severity: low
#Description: Setting the password warning age enables users to make the change at a practical time.
#Rule Title: Users must be warned 7 days in advance of password expiration.
#Version: RHEL-06-000054

#Check Content: To check the password warning age, run the command: 

#$ grep PASS_WARN_AGE /etc/login.defs

#The DoD requirement is 7. 
#If it is not set to the required value, this is a finding.


#Fix Text: To specify how many days prior to password expiration that a warning will be issued to users, edit the file "/etc/login.defs" and add or correct the following line, replacing [DAYS] appropriately: 

#PASS_WARN_AGE [DAYS]

#The DoD requirement is 7.
if grep PASS_WARN_AGE /etc/login.defs|grep "7"; then
echo "This machine is RHEL-06-000054 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000054 Compliant"
else
echo "This machine isn't RHEL-06-000054 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000054 Compliant"
var_accounts_password_warn_age_login_defs="7"
grep -q ^PASS_WARN_DAYS /etc/login.defs && \
  sed -i "s/PASS_WARN_DAYS.*/PASS_WARN_DAYS     $var_accounts_password_warn_age_login_defs/g" /etc/login.defs
if ! [ $? -eq 0 ]; then
    echo "PASS_WARN_DAYS      $var_accounts_password_warn_age_login_defs" >> /etc/login.defs
fi
fi
