#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38528
#Group Title: SRG-OS-999999
#Version: RHEL-06-000088
#Severity: low
#Description: The presence of "martian" packets (which have impossible addresses) as well as spoofed packets, source-routed packets, and redirects could be a sign of nefarious network activity. Logging these packets enables this activity to be detected.
#Rule Title: The system must log Martian packets.
#Version: RHEL-06-000088

#Check Content: The status of the "net.ipv4.conf.all.log_martians" kernel parameter can be queried by running the following command: 

#$ sysctl net.ipv4.conf.all.log_martians

#The output of the command should indicate a value of "1". If this value is not the default value, investigate how it could have been adjusted at runtime, and verify it is not set improperly in "/etc/sysctl.conf". 
#If the correct value is not returned, this is a finding.


#Fix Text: To set the runtime status of the "net.ipv4.conf.all.log_martians" kernel parameter, run the following command: 

# sysctl -w net.ipv4.conf.all.log_martians=1

#If this is not the system's default value, add the following line to "/etc/sysctl.conf": 

#net.ipv4.conf.all.log_martians = 1
if sysctl net.ipv4.conf.all.log_martians|grep "1"; then
echo "This machine is RHEL-06-000088 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000088 Compliant"
else
echo "This machine isn't RHEL-06-000088 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000088 Compliant"
if grep --silent ^net.ipv4.conf.all.log_martians /etc/sysctl.conf ; then
	sed -i 's/^net.ipv4.conf.all.log_martians.*/net.ipv4.conf.all.log_martians = 1/g' /etc/sysctl.conf
	sysctl -w net.ipv4.conf.all.log_martians=1
else
	echo "" >> /etc/sysctl.conf
	echo "# Set net.ipv4.conf.all.log_martians to 1 per security requirements" >> /etc/sysctl.conf
	echo "net.ipv4.conf.all.log_martians = 1" >> /etc/sysctl.conf
	sysctl -w net.ipv4.conf.all.log_martians=1
fi

fi
