#!/bin/bash
#Created by Matthew M. Conley / SimonTek


#Group ID: V-38446
#Group Title: SRG-OS-999999
#Version: RHEL-06-000521
#Severity: medium
#Description: A number of system services utilize email messages sent to the root user to notify system administrators of active or impending issues.  These messages must be forwarded to at least one monitored email address.
#Rule Title: The mail system must forward all mail for root to one or more system administrators.
#Version: RHEL-06-000521

#Check Content: Find the list of alias maps used by the Postfix mail server:

# postconf alias_maps

#Query the Postfix alias maps for an alias for "root":

# postmap -q root <alias_map>

#If there are no aliases configured for root that forward to a monitored email address, this is a finding.


#Fix Text: Set up an alias for root that forwards to a monitored email address:

# echo "root: <system.administrator>@mail.mil" >> /etc/aliases
# newaliases

if rpm -qa |grep postfix; then
        if postconf alias_maps|grep root; then
        echo "This machine isn't RHEL-06-000521 Compliant" >> /var/log/Stig
        echo "This machine isn't RHEL-06-000521 Compliant"
        echo "root: <system.administrator>@mail.mil" >> /etc/aliases
        newaliases
        else
        echo "This machine is RHEL-06-000521 Compliant" >> /var/log/Stig
        echo "This machine is RHEL-06-000521 Compliant"
        fi
else
echo "This machine doesn't have Postfix installed" >> /var/log/Stig
echo "This machine doesn't have Postfix installed"
fi

