#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38569
#Group Title: SRG-OS-000069
#Version: RHEL-06-000057
#Severity: low
#Description: Requiring a minimum number of uppercase characters makes password guessing attacks more difficult by ensuring a larger search space.
#Rule Title: The system must require passwords to contain at least one uppercase alphabetic character.
#Version: RHEL-06-000057

#Check Content: To check how many uppercase characters are required in a password, run the following command: 

#$ grep pam_cracklib /etc/pam.d/system-auth

#The "ucredit" parameter (as a negative number) will indicate how many uppercase characters are required. The DoD requires at least one uppercase character in a password. This would appear as "ucredit=-1". 
#If ucredit is not found or not set to the required value, this is a finding.


#Fix Text: The pam_cracklib module's "ucredit=" parameter controls requirements for usage of uppercase letters in a password. When set to a negative number, any password will be required to contain that many uppercase characters. When set to a positive number, pam_cracklib will grant +1 additional length credit for each uppercase character. Add "ucredit=-1" after pam_cracklib.so to require use of an uppercase character in passwords.

if grep pam_cracklib /etc/pam.d/system-auth|grep ucredit=-; then
echo "This machine is RHEL-06-000057 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000057 Compliant"
else
echo "This machine isn't RHEL-06-000057 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000057 Compliant"
sed -i '/^password    requisite/ s/$/ ucredit=-1/' /etc/pam.d/system-auth
fi