#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38673
#Group Title: SRG-OS-000265
#Version: RHEL-06-000307
#Severity: medium
#Description: By default, AIDE does not install itself for periodic execution. Periodically running AIDE may reveal unexpected changes in installed files.
#Rule Title: The operating system must ensure unauthorized, security-relevant configuration changes detected are tracked.
#Version: RHEL-06-000307

#Check Content: To determine that periodic AIDE execution has been scheduled, run the following command: 
# grep aide /etc/crontab
#If there is no output, this is a finding.
#Fix Text: AIDE should be executed on a periodic basis to check for changes. To implement a daily execution of AIDE at 4:05am using cron, add the following line to /etc/crontab: 
#05 4 * * * root /usr/sbin/aide --check
#AIDE can be executed periodically through other means; this is merely one example.

if grep aide /etc/crontab; then
echo "This machine is RHEL-06-000307 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000307 Compliant"
else
echo "This machine isn't RHEL-06-000307 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000307 Compliant"
echo "05 4 * * * root /usr/sbin/aide --check" >> /etc/crontab
fi