#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38651
#Group Title: SRG-OS-999999
#Version: RHEL-06-000342
#Severity: low
#Description: The umask value influences the permissions assigned to files when they are created. A misconfigured umask value could result in files with excessive permissions that can be read and/or written to by unauthorized users.
#Rule Title: The system default umask for the bash shell must be 077.
#Version: RHEL-06-000342

#Check Content: Verify the "umask" setting is configured correctly in the "/etc/bashrc" file by running the following command: 
# grep "umask" /etc/bashrc
#All output must show the value of "umask" set to 077, as shown below: 
# grep "umask" /etc/bashrc
#umask 077
#umask 077
#If the above command returns no output, or if the umask is configured incorrectly, this is a finding.
#Fix Text: To ensure the default umask for users of the Bash shell is set properly, add or correct the "umask" setting in "/etc/bashrc" to read as follows: 
#umask 077

if grep "umask" /etc/bashrc|grep 077; then
echo "This machine is RHEL-06-000342 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000342 Compliant"
else
echo "This machine isn't RHEL-06-000342 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000342 Compliant"
var_umask_for_bashrc="077"
grep -q umask /etc/bashrc && \
  sed -i "s/umask.*/umask $var_umask_for_bashrc/g" /etc/bashrc
if ! [ $? -eq 0 ]; then
    echo "umask $var_umask_for_bashrc" >> /etc/bashrc
fi
fi