#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38618
#Group Title: SRG-OS-999999
#Version: RHEL-06-000246
#Severity: low
#Description: Because the Avahi daemon service keeps an open network port, it is subject to network attacks. Its functionality is convenient but is only appropriate if the local network can be trusted.
#Rule Title: The avahi service must be disabled.
#Version: RHEL-06-000246

#Check Content: To check that the "avahi-daemon" service is disabled in system boot configuration, run the following command: 

# chkconfig "avahi-daemon" --list

#Output should indicate the "avahi-daemon" service has either not been installed, or has been disabled at all runlevels, as shown in the example below: 

# chkconfig "avahi-daemon" --list
#"avahi-daemon" 0:off 1:off 2:off 3:off 4:off 5:off 6:off

#Run the following command to verify "avahi-daemon" is disabled through current runtime configuration: 

# service avahi-daemon status

#If the service is disabled the command will return the following output: 

#avahi-daemon is stopped


#If the service is running, this is a finding.


#Fix Text: The "avahi-daemon" service can be disabled with the following command: 

# chkconfig avahi-daemon off
if rpm -qa |grep avahi-0; then
echo "This machine isn't RHEL-06-000246 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000246 Compliant"
service avahi-daemon stop
chkconfig avahi-daemon off
else
echo "This machine is RHEL-06-000246 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000246 Compliant"
fi
