#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38455
#Group Title: SRG-OS-999999
#Version: RHEL-06-000001
#Severity: low
#Description: The "/tmp" partition is used as temporary storage by many programs. Placing "/tmp" in its own partition enables the setting of more restrictive mount options, which can help protect programs which use it.
#Rule Title: The system must use a separate file system for /tmp.
#Version: RHEL-06-000001

#Check Content: Run the following command to determine if "/tmp" is on its own partition or logical volume: 

#$ mount | grep "on /tmp "

#If "/tmp" has its own partition or volume group, a line will be returned. 
#If no line is returned, this is a finding.


#Fix Text: The "/tmp" directory is a world-writable directory used for temporary file storage. Ensure it has its own partition or logical volume at installation time, or migrate it using LVM.
if mount | grep "on /tmp ";then
echo "All is set"
echo "This machine is RHEL-06-000001 Compliant" >> /var/log/Stig
else
echo "This machine isn't RHEL-06-000001 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000001 Compliant"
fi
