#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38467
#Group Title: SRG-OS-000044
#Version: RHEL-06-000004
#Severity: low
#Description: Placing "/var/log/audit" in its own partition enables better separation between audit files and other files, and helps ensure that auditing cannot be halted due to the partition running out of space.
#Rule Title: The system must use a separate file system for the system audit data path.
#Version: RHEL-06-000004

#Check Content: Run the following command to determine if "/var/log/audit" is on its own partition or logical volume: 

#$ mount | grep "on /var/log/audit "

#If "/var/log/audit" has its own partition or volume group, a line will be returned. 
#If no line is returned, this is a finding.


#Fix Text: Audit logs are stored in the "/var/log/audit" directory. Ensure that it has its own partition or logical volume at installation time, or migrate it later using LVM. Make absolutely certain that it is large enough to store all audit logs that will be created by the auditing daemon.
if mount | grep "on /var/log/audit "; then
echo "This machine is RHEL-06-000004 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000004 Compliant"
else
echo "This machine isn't RHEL-06-000004 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000004 Compliant"
fi
