#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38538
#Group Title: SRG-OS-000241
#Version: RHEL-06-000177
#Severity: low
#Description: In addition to auditing new user and group accounts, these watches will alert the system administrator(s) to any modifications. Any unexpected users, groups, or modifications should be investigated for legitimacy.
#Rule Title: The operating system must automatically audit account termination.
#Version: RHEL-06-000177

#Check Content: To determine if the system is configured to audit account changes, run the following command: 

#auditctl -l | egrep '(/etc/passwd|/etc/shadow|/etc/group|/etc/gshadow|/etc/security/opasswd)'

#If the system is configured to watch for account changes, lines should be returned for each file specified (and with "perm=wa" for each). 
#If the system is not configured to audit account changes, this is a finding.


#Fix Text: Add the following to "/etc/audit/audit.rules", in order to capture events that modify account changes: 

# audit_account_changes
#-w /etc/group -p wa -k audit_account_changes
#-w /etc/passwd -p wa -k audit_account_changes
#-w /etc/gshadow -p wa -k audit_account_changes
#-w /etc/shadow -p wa -k audit_account_changes
#-w /etc/security/opasswd -p wa -k audit_account_changes

echo "RHEL-06-000177 is covered by RHEL-06-000175 " >> /var/log/Stig
echo "RHEL-06-000177 is covered by RHEL-06-000175 "