#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38682
#Group Title: SRG-OS-000034
#Version: RHEL-06-000315
#Severity: medium
#Description: If Bluetooth functionality must be disabled, preventing the kernel from loading the kernel module provides an additional safeguard against its activation.
#Rule Title: The Bluetooth kernel module must be disabled.
#Version: RHEL-06-000315

#Check Content: If the system is configured to prevent the loading of the "bluetooth" kernel module, it will contain lines inside any file in "/etc/modprobe.d" or the deprecated"/etc/modprobe.conf". These lines instruct the module loading system to run another program (such as "/bin/true") upon a module "install" event. Run the following command to search for such lines in all files in "/etc/modprobe.d" and the deprecated "/etc/modprobe.conf": 

#$ grep -r bluetooth /etc/modprobe.conf /etc/modprobe.d

#If the system is configured to prevent the loading of the "net-pf-31" kernel module, it will contain lines inside any file in "/etc/modprobe.d" or the deprecated"/etc/modprobe.conf". These lines instruct the module loading system to run another program (such as "/bin/true") upon a module "install" event. Run the following command to search for such lines in all files in "/etc/modprobe.d" and the deprecated "/etc/modprobe.conf": 

#$ grep -r net-pf-31 /etc/modprobe.conf /etc/modprobe.d
#If no line is returned, this is a finding.
#Fix Text: The kernel's module loading system can be configured to prevent loading of the Bluetooth module. Add the following to the appropriate "/etc/modprobe.d" configuration file to prevent the loading of the Bluetooth module: 

#install net-pf-31 /bin/true
#install bluetooth /bin/true

if grep -r bluetooth /etc/modprobe.d; then
echo "This machine is RHEL-06-000315 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000315 Compliant"
else
echo "This machine isn't RHEL-06-000315 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000315 Compliant"
echo "install bluetooth /bin/false" > /etc/modprobe.d/bluetooth.conf
fi

if grep -r net-pf-31 /etc/modprobe.d ; then
echo "This machine is RHEL-06-000315 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000315 Compliant"
else
echo "This machine isn't RHEL-06-000315 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000315 Compliant"
echo "install net-pf-31 /bin/false" > /etc/modprobe.d/net-pf-31.conf
fi
