#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38655
#Group Title: SRG-OS-000035
#Version: RHEL-06-000271
#Severity: low
#Description: Allowing users to execute binaries from removable media such as USB keys exposes the system to potential compromise.
#Rule Title: The noexec option must be added to removable media partitions.
#Version: RHEL-06-000271

#Check Content: To verify that binaries cannot be directly executed from removable media, run the following command: 
# grep noexec /etc/fstab
#The output should show "noexec" in use. 
#If it does not, this is a finding.
#Fix Text: The "noexec" mount option prevents the direct execution of binaries on the mounted filesystem. Users should not be allowed to execute binaries that exist on partitions mounted from removable media (such as a USB key). The "noexec" option prevents code from being executed directly from the media itself, and may therefore provide a line of defense against certain types of worms or malicious code. Add the "noexec" option to the fourth column of "/etc/fstab" for the line which controls mounting of any removable media partitions.


if grep noexec /etc/fstab; then
echo "This machine is RHEL-06-000271 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000271 Compliant"
else
echo "This machine isn't RHEL-06-000271 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000271 Compliant"

fi