#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38476
#Group Title: SRG-OS-000090
#Version: RHEL-06-000008
#Severity: high
#Description: This key is necessary to cryptographically verify packages are from Red Hat.
#Rule Title: Vendor-provided cryptographic certificates must be installed to verify the integrity of system software.
#Version: RHEL-06-000008

#Check Content: To ensure that the GPG key is installed, run: 

#$ rpm -q --queryformat "%{SUMMARY}\n" gpg-pubkey

#The command should return the string below: 

#gpg(Red Hat, Inc. (release key <security@redhat.com>)


#If the Red Hat GPG Key is not installed, this is a finding.


#Fix Text: To ensure the system can cryptographically verify base software packages come from Red Hat (and to connect to the Red Hat Network to receive them if desired), the Red Hat GPG key must properly be installed. To ensure the GPG key is installed, run: 

# rhn_register


if rpm -q --queryformat "%{SUMMARY}\n" gpg-pubkey |grep "Red Hat, Inc"; then
echo "This machine is RHEL-06-000008 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000008 Compliant"
else
echo "This machine isn't RHEL-06-000008 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000008 Compliant"
rhn_register
fi
