#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38461
#Group Title: SRG-OS-999999
#Version: RHEL-06-004444
#Severity: medium
#Description: The "/etc/group" file contains information regarding groups that are configured on the system. Protection of this file is important for system security.
#Rule Title: The /etc/group file must have mode 0644 or less permissive.
#Version: RHEL-06-004444

#Check Content: To check the permissions of "/etc/group", run the command: 

#$ ls -l /etc/group

#If properly configured, the output should indicate the following permissions: "-rw-r--r--" 
#If it does not, this is a finding.


#Fix Text: To properly set the permissions of "/etc/group", run the command: 

# chmod 644 /etc/group
if ls -l /etc/group |grep "rw-r--r--"; then
echo "This machine is RHEL-06-000444 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000444 Compliant"
else
echo "This machine isn't RHEL-06-000444 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000444 Compliant"
chmod 644 /etc/group
fi