#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38484
#Group Title: SRG-OS-000025
#Version: RHEL-06-000507
#Severity: medium
#Description: Users need to be aware of activity that occurs regarding their account. Providing users with information regarding the date and time of their last successful login allows the user to determine if any unauthorized activity has occurred and gives them an opportunity to notify administrators.

#At ssh login, a user must be presented with the last successful login date and time.
#Rule Title: The operating system, upon successful logon, must display to the user the date and time of the last logon or access via ssh.
#Version: RHEL-06-000507
#Check Content: Verify the value associated with the "PrintLastLog" keyword in /etc/ssh/sshd_config:
# grep -i PrintLastLog /etc/ssh/sshd_config
#If the value is not set to "yes", this is a finding.  If the "PrintLastLog" keyword is not present, this is not a finding.
#Fix Text: Update the "PrintLastLog" keyword to "yes" in /etc/ssh/sshd_config:
#While it is acceptable to remove the keyword entirely since the default action for the SSH daemon is to print the last login date and time, it is preferred to have the value explicitly documented.

#if grep -i PrintLastLog /etc/ssh/sshd_config|grep -v 'no'|grep -v '^#'; then
if egrep '^[^#]*PrintLastLog' /etc/ssh/sshd_config|grep -v no; then
echo "This machine is RHEL-06-000507 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000507 Compliant"
else
echo "This machine isn't RHEL-06-000507 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000507 Compliant"
sed -i 's@^#PrintLastLog.*@PrintLastLog yes@g' /etc/ssh/sshd_config
fi
