#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38560
#Group Title: SRG-OS-000145
#Version: RHEL-06-000116
#Severity: medium
#Description: The "iptables" service provides the system's host-based firewalling capability for IPv4 and ICMP.
#Rule Title: The operating system must connect to external networks or information systems only through managed IPv4 interfaces consisting of boundary protection devices arranged in accordance with an organizational security architecture.
#Version: RHEL-06-000116

#Check Content: If the system is a cross-domain system, this is not applicable.
#Run the following command to determine the current status of the "iptables" service: 
# service iptables status
#If the service is enabled, it should return the following: 
#iptables is running...
#If the service is not running, this is a finding.
#Fix Text: The "iptables" service can be enabled with the following command: 
# chkconfig iptables on
if service iptables status| grep "filter"; then 
echo "This machine is RHEL-06-000116 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000116 Compliant"
else
echo "This machine isn't RHEL-06-000116 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000116 Compliant"
chkconfig iptables on
/etc/init.d/iptables restart
fi