#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38668
#Group Title: SRG-OS-999999
#Version: RHEL-06-000286
#Severity: high
#Description: A locally logged-in user who presses Ctrl-Alt-Delete, when at the console, can reboot the system. If accidentally pressed, as could happen in the case of mixed OS environment, this can create the risk of short-term loss of availability of systems due to unintentional reboot. In the GNOME graphical environment, risk of unintentional reboot from the Ctrl-Alt-Delete sequence is reduced because the user will be prompted before any action is taken.
#Rule Title: The x86 Ctrl-Alt-Delete key sequence must be disabled.
#Version: RHEL-06-000286

#Check Content: Determine what actions the system takes when the Ctrl-Alt-Delete key sequence is pressed, run the following command:

#  cat `grep -l control-alt-delete /etc/init/*`

#Examine all lines following the "start on control-alt-delete" line in any files found.  By default, the system uses "/etc/init/control-alt-delete.conf" to reboot the system with the following command when the Ctrl-Alt-Delete key sequence is pressed: 

#exec /sbin/shutdown -r now "Control-Alt-Delete pressed"

#If the system is configured to run any shutdown command, this is a finding.


#Fix Text: Configure the system to log a message instead of rebooting the system by altering the "shutdown" line in "/etc/init/control-alt-delete.conf" to read as follows: 

#exec /usr/bin/logger -p security.info "Ctrl-Alt-Delete pressed"

if cat `grep -l control-alt-delete /etc/init/*`|grep "logger" ; then
echo "This machine is RHEL-06-000286 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000286 Compliant"
else
echo "This machine isn't RHEL-06-000286 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000286 Compliant"
sed -i 's@exec /sbin/shutdown -r now @exec /usr/bin/logger -p security.info@g' /etc/init/control-alt-delete.conf 
fi
