#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38597
#Group Title: SRG-OS-999999
#Version: RHEL-06-000079
#Severity: medium
#Description: ExecShield uses the segmentation feature on all x86 systems to prevent execution in memory higher than a certain address. It writes an address as a limit in the code segment descriptor, to control where code can be executed, on a per-process basis. When the kernel places a process's memory regions such as the stack and heap higher than this address, the hardware prevents execution in that address range.
#Rule Title: The system must limit the ability of processes to have simultaneous write and execute access to memory.
#Version: RHEL-06-000079

#Check Content: The status of the "kernel.exec-shield" kernel parameter can be queried by running the following command: 
#$ sysctl kernel.exec-shield
#The output of the command should indicate a value of "1". If this value is not the default value, investigate how it could have been adjusted at runtime, and verify it is not set improperly in "/etc/sysctl.conf". 
#If the correct value is not returned, this is a finding.
#Fix Text: To set the runtime status of the "kernel.exec-shield" kernel parameter, run the following command: 
# sysctl -w kernel.exec-shield=1
#If this is not the system's default value, add the following line to "/etc/sysctl.conf": 
#kernel.exec-shield = 1

if grep ^kernel.exec-shield /etc/sysctl.conf|grep 1; then
echo "This machine is RHEL-06-000079 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000079 Compliant"
else
echo "This machine isn't RHEL-06-000079 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000079 Compliant"
if grep --silent ^kernel.exec-shield /etc/sysctl.conf ; then
	sed -i 's/^kernel.exec-shield.*/kernel.exec-shield = 1/g' /etc/sysctl.conf
else
	echo "" >> /etc/sysctl.conf
	echo "# Exec-Shield" >> /etc/sysctl.conf
	echo "kernel.exec-shield = 1" >> /etc/sysctl.conf
fi

fi
