#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38495
#Group Title: SRG-OS-000057
#Version: RHEL-06-000384
#Severity: medium
#Description: If non-privileged users can write to audit logs, audit trails can be modified or destroyed.
#Rule Title: Audit log files must be owned by root.
#Version: RHEL-06-000384

#Check Content: Run the following command to check the owner of the system audit logs: 

#grep "^log_file" /etc/audit/auditd.conf|sed s/^[^\/]*//|xargs stat -c %U:%n

#Audit logs must be owned by root. 
#If they are not, this is a finding.


#Fix Text: Change the owner of the audit log files with the following command: 

# chown root [audit_file]

if grep "^log_file" /etc/audit/auditd.conf|sed s/^[^\/]*//|xargs stat -c %U:%n |grep root; then
echo "This machine is RHEL-06-000384 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000384 Compliant"
else
echo "This machine isn't RHEL-06-000384 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000384 Compliant"
chown root /var/log/audit/audit.log
fi