#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38570
#Group Title: SRG-OS-000266
#Version: RHEL-06-000058
#Severity: low
#Description: Requiring a minimum number of special characters makes password guessing attacks more difficult by ensuring a larger search space.
#Rule Title: The system must require passwords to contain at least one special character.
#Version: RHEL-06-000058

#Check Content: To check how many special characters are required in a password, run the following command: 

#$ grep pam_cracklib /etc/pam.d/system-auth

#The "ocredit" parameter (as a negative number) will indicate how many special characters are required. The DoD requires at least one special character in a password. This would appear as "ocredit=-1". 
#If ocredit is not found or not set to the required value, this is a finding.


#Fix Text: The pam_cracklib module's "ocredit=" parameter controls requirements for usage of special (or ``other'') characters in a password. When set to a negative number, any password will be required to contain that many special characters. When set to a positive number, pam_cracklib will grant +1 additional length credit for each special character. Add "ocredit=-1" after pam_cracklib.so to require use of a special character in passwords.

if  grep pam_cracklib /etc/pam.d/system-auth|grep ocredit=-; then
echo "This machine is RHEL-06-000058 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000058 Compliant"
else
echo "This machine isn't RHEL-06-000058 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000058 Compliant"
sed -i '/^password    requisite/ s/$/ ocredit=-1/' /etc/pam.d/system-auth
fi
