#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38680
#Group Title: SRG-OS-000046
#Version: RHEL-06-000313
#Severity: medium
#Description: Email sent to the root account is typically aliased to the administrators of the system, who can take appropriate action.
#Rule Title: The audit system must identify staff members to receive notifications of audit log storage volume capacity issues.
#Version: RHEL-06-000313

#Check Content: Inspect "/etc/audit/auditd.conf" and locate the following line to determine if the system is configured to send email to an account when it needs to notify an administrator: 

#action_mail_acct = root


#If auditd is not configured to send emails per identified actions, this is a finding.


#Fix Text: The "auditd" service can be configured to send email to a designated account in certain situations. Add or correct the following line in "/etc/audit/auditd.conf" to ensure that administrators are notified via email for those situations: 

#action_mail_acct = root

if grep "action_mail_acct =" /etc/audit/auditd.conf |grep root; then
echo "This machine is RHEL-06-000313 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000313 Compliant"
else
echo "This machine isn't RHEL-06-000313 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000313 Compliant"
sed -i 's@action_mail_acct =.*@action_mail_acct = root@g' /etc/audit/auditd.conf
fi