#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38468
#Group Title: SRG-OS-005107
#Version: RHEL-06-000510
#Severity: medium
#Description: Taking appropriate action in case of a filled audit storage volume will minimize the possibility of losing audit records.
#Rule Title: The audit system must take appropriate action when the audit storage volume is full.
#Version: RHEL-06-000510

#Check Content: Inspect "/etc/audit/auditd.conf" and locate the following line to determine if the system is configured to take appropriate action when the audit storage volume is full:

# grep disk_full_action /etc/audit/auditd.conf
#disk_full_action = [ACTION]


#If the system is configured to "suspend" when the volume is full or "ignore" that it is full, this is a finding.


#Fix Text: The "auditd" service can be configured to take an action when disk space starts to run low. Edit the file "/etc/audit/auditd.conf". Modify the following line, substituting [ACTION] appropriately: 

#disk_full_action = [ACTION]

#Possible values for [ACTION] are described in the "auditd.conf" man page. These include: 

#"ignore"
#"syslog"
#"exec"
#"suspend"
#"single"
#"halt"
#Set this to "syslog", "exec", "single", or "halt".
if grep disk_full_action /etc/audit/auditd.conf|grep -i SUSPEND; then
echo "This machine is RHEL-06-000510 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000510 Compliant"
else
echo "This machine isn't RHEL-06-000510 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000510 Compliant"
sed -i 's@disk_full_action = SUSPEND@disk_full_action = SINGLE@g' /etc/audit/auditd.conf
fi

