#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38529
#Group Title: SRG-OS-999999
#Version: RHEL-06-000089
#Severity: medium
#Description: Accepting source-routed packets in the IPv4 protocol has few legitimate uses. It should be disabled unless it is absolutely required.
#Rule Title: The system must not accept IPv4 source-routed packets by default.
#Version: RHEL-06-000089

#Check Content: The status of the "net.ipv4.conf.default.accept_source_route" kernel parameter can be queried by running the following command: 

#$ sysctl net.ipv4.conf.default.accept_source_route

#The output of the command should indicate a value of "0". If this value is not the default value, investigate how it could have been adjusted at runtime, and verify it is not set improperly in "/etc/sysctl.conf". 
#If the correct value is not returned, this is a finding.


#Fix Text: To set the runtime status of the "net.ipv4.conf.default.accept_source_route" kernel parameter, run the following command: 

# sysctl -w net.ipv4.conf.default.accept_source_route=0

#If this is not the system's default value, add the following line to "/etc/sysctl.conf": 

#net.ipv4.conf.default.accept_source_route = 0
if sysctl net.ipv4.conf.default.accept_source_route|grep "= 0"; then
echo "This machine is RHEL-06-000089 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000089 Compliant"
else
echo "This machine isn't RHEL-06-000089 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000089 Compliant"
sysctl -w net.ipv4.conf.default.accept_source_route=0
fi