#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38649
#Group Title: SRG-OS-999999
#Version: RHEL-06-000343
#Severity: low
#Description: The umask value influences the permissions assigned to files when they are created. A misconfigured umask value could result in files with excessive permissions that can be read and/or written to by unauthorized users.
#Rule Title: The system default umask for the csh shell must be 077.
#Version: RHEL-06-000343

#Check Content: Verify the "umask" setting is configured correctly in the "/etc/csh.cshrc" file by running the following command: 
# grep "umask" /etc/csh.cshrc
#All output must show the value of "umask" set to 077, as shown in the below: 
# grep "umask" /etc/csh.cshrc
#umask 077
#If the above command returns no output, or if the umask is configured incorrectly, this is a finding.
#Fix Text: To ensure the default umask for users of the C shell is set properly, add or correct the "umask" setting in "/etc/csh.cshrc" to read as follows: 
#umask 077

if grep "umask" /etc/csh.cshrc|grep 077; then
echo "This machine is RHEL-06-000343 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000343 Compliant"
else
echo "This machine isn't RHEL-06-000343 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000343 Compliant"
var_umask_for_cshrc="077"
grep -q umask /etc/csh.cshrc && \
  sed -i "s/umask.*/umask $var_umask_for_cshrc/g" /etc/csh.cshrc
if ! [ $? -eq 0 ]; then
    echo "umask $var_umask_for_cshrc" >> /etc/csh.cshrc
fi
fi
