#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38516
#Group Title: SRG-OS-000096
#Version: RHEL-06-000126
#Severity: low
#Description: Disabling RDS protects the system against exploitation of any flaws in its implementation.
#Rule Title: The Reliable Datagram Sockets (RDS) protocol must be disabled unless required.
#Version: RHEL-06-000126

#Check Content: If the system is configured to prevent the loading of the "rds" kernel module, it will contain lines inside any file in "/etc/modprobe.d" or the deprecated"/etc/modprobe.conf". These lines instruct the module loading system to run another program (such as "/bin/true") upon a module "install" event. Run the following command to search for such lines in all files in "/etc/modprobe.d" and the deprecated "/etc/modprobe.conf": 

#$ grep -r rds /etc/modprobe.conf /etc/modprobe.d


#If no line is returned, this is a finding.


#Fix Text: The Reliable Datagram Sockets (RDS) protocol is a transport layer protocol designed to provide reliable high- bandwidth, low-latency communications between nodes in a cluster. To configure the system to prevent the "rds" kernel module from being loaded, add the following line to a file in the directory "/etc/modprobe.d": 

#install rds /bin/true

if grep -r rds /etc/modprobe.d/ ; then
echo "This machine is RHEL-06-000126 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000126 Compliant"
else
echo "This machine isn't RHEL-06-000126 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000126 Compliant"
echo "install rds /bin/false" > /etc/modprobe.d/rds.conf
fi
