#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38666
#Group Title: SRG-OS-000270
#Version: RHEL-06-000284
#Severity: high
#Description: Virus scanning software can be used to detect if a system has been compromised by computer viruses, as well as to limit their spread to other systems.
#Rule Title: The system must use and update a DoD-approved virus scan program.
#Version: RHEL-06-000284

#Check Content: Inspect the system for a cron job or system service which executes a virus scanning tool regularly. 
#To verify the McAfee command line scan tool (uvscan) is scheduled for regular execution, run the following command to check for a cron job: 

# grep uvscan /etc/cron* /var/spool/cron/*

#This will reveal if and when the uvscan program will be run. 
#To check on the age of uvscan virus definition files, run the following command: 

# cd /usr/local/uvscan
# ls -la avvscan.dat avvnames.dat avvclean.dat
#The uvscan virus definitions should not be older than seven days.
#If virus scanning software does not run daily, or has signatures that are out of date, this is a finding.
#Fix Text: Install virus scanning software, which uses signatures to search for the presence of viruses on the filesystem. The McAfee uvscan virus scanning tool is provided for DoD systems. Ensure virus definition files are no older than 7 days, or their last release. Configure the virus scanning software to perform scans dynamically on all accessed files. If this is not possible, configure the system to scan all altered files on the system on a daily basis. If the system processes inbound SMTP mail, configure the virus scanner to scan all received mail.

if grep -r uvscan /etc/cron* ; then
echo "This machine is RHEL-06-000284 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000284 Compliant"
else
echo "This machine isn't RHEL-06-000284 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000284 Compliant"
echo '/usr/local/bin/uvscan --secure -vr --summary --ignore-links  --exclude /usr/local/uvscan/exfile /  > /var/log/vscanresults.txt' > /etc/cron.weekly/av.cron
chmod 0700 /etc/cron.weekly/av.cron

fi


#curdttm=`date +%Y%m%d%H%M`
#/usr/local/bin/uvscan --secure -vr --summary --ignore-links  --exclude /usr/local/uvscan/exfile /  > /var/log/vscanresults.txt
#grep -v 'is OK' /var/log/AV/vscanresults.txt > /var/log/AV/tempresults.txt
#mv -f /var/log/AV/tempresults.txt /var/log/AV/vscanresults.txt

#mv /var/log/AV/vscanresults.txt /var/log/AV/vscanresults.${curdttm}.txt
#/usr/bin/xz /var/log/AV/vscanresults.${curdttm}.txt

