#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38647
#Group Title: SRG-OS-999999
#Version: RHEL-06-000344
#Severity: low
#Description: The umask value influences the permissions assigned to files when they are created. A misconfigured umask value could result in files with excessive permissions that can be read and/or written to by unauthorized users.
#Rule Title: The system default umask in /etc/profile must be 077.
#Version: RHEL-06-000344

#Check Content: Verify the "umask" setting is configured correctly in the "/etc/profile" file by running the following command: 
# grep "umask" /etc/profile
#All output must show the value of "umask" set to 077, as shown in the below: 

# grep "umask" /etc/profile
#umask 077
#If the above command returns no output, or if the umask is configured incorrectly, this is a finding.
#Fix Text: To ensure the default umask controlled by "/etc/profile" is set properly, add or correct the "umask" setting in "/etc/profile" to read as follows: 
#umask 077

if grep "umask" /etc/profile|grep 077; then
echo "This machine is RHEL-06-000344 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000344 Compliant"
else
echo "This machine isn't RHEL-06-000344 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000344 Compliant"
var_umask_for_profile="077"
grep -q umask /etc/profile && \
  sed -i "s/umask.*/umask $var_umask_for_profile/g" /etc/profile
if ! [ $? -eq 0 ]; then
    echo "umask $var_umask_for_profile" >> /etc/profile
fi
fi
