#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38579
#Group Title: SRG-OS-999999
#Version: RHEL-06-000065
#Severity: medium
#Description: Only root should be able to modify important boot parameters.
#Rule Title: The system boot loader configuration file(s) must be owned by root.
#Version: RHEL-06-000065

#Check Content: To check the ownership of "/etc/grub.conf", run the command: 

#$ ls -lL /etc/grub.conf

#If properly configured, the output should indicate the following owner: "root" 
#If it does not, this is a finding.


#Fix Text: The file "/etc/grub.conf" should be owned by the "root" user to prevent destruction or modification of the file. To properly set the owner of "/etc/grub.conf", run the command: 

# chown root /etc/grub.conf
if ls -lL /etc/grub.conf |grep "1 root"; then
echo "This machine is RHEL-06-000065 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000065 Compliant"
else
echo "This machine isn't RHEL-06-000065 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000065 Compliant"
chown root /etc/grub.conf
fi