#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38604
#Group Title: SRG-OS-000096
#Version: RHEL-06-000221
#Severity: medium
#Description: Disabling the "ypbind" service ensures the system is not acting as a client in a NIS or NIS+ domain.
#Rule Title: The ypbind service must not be running.
#Version: RHEL-06-000221

#Check Content: To check that the "ypbind" service is disabled in system boot configuration, run the following command: 

# chkconfig "ypbind" --list

#Output should indicate the "ypbind" service has either not been installed, or has been disabled at all runlevels, as shown in the example below: 

# chkconfig "ypbind" --list
#"ypbind" 0:off 1:off 2:off 3:off 4:off 5:off 6:off
#Run the following command to verify "ypbind" is disabled through current runtime configuration: 
# service ypbind status
#If the service is disabled the command will return the following output: 
#ypbind is stopped
#If the service is running, this is a finding.
#Fix Text: The "ypbind" service, which allows the system to act as a client in a NIS or NIS+ domain, should be disabled. The "ypbind" service can be disabled with the following command: 

# chkconfig ypbind off

if chkconfig --list |grep ypbind; then
echo "This machine isn't RHEL-06-000221 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000221 Compliant"
chkconfig ypbind off
/etc/init.d/ypbind stop
else
echo "This machine is RHEL-06-000221 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000221 Compliant"
fi