#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38448
#Group Title: SRG-OS-999999
#Version: RHEL-06-000037
#Severity: medium
#Description: The "/etc/gshadow" file contains group password hashes. Protection of this file is critical for system security.
#Rule Title: The /etc/gshadow file must be group-owned by root.
#Version: RHEL-06-000037

#Check Content: To check the group ownership of "/etc/gshadow", run the command: 

#$ ls -l /etc/gshadow

#If properly configured, the output should indicate the following group-owner. "root" 
#If it does not, this is a finding.


#Fix Text: To properly set the group owner of "/etc/gshadow", run the command: 

# chgrp root /etc/gshadow
if ls -l /etc/gshadow |grep -v "root"; then
echo "This machine isn't RHEL-06-000037 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000037 Compliant"
chgrp root /etc/gshadow
else
echo "This machine is RHEL-06-000037 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000037 Compliant"
fi
