#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38572
#Group Title: SRG-OS-000072
#Version: RHEL-06-000060
#Severity: low
#Description: Requiring a minimum number of different characters during password changes ensures that newly changed passwords should not resemble previously compromised ones. Note that passwords which are changed on compromised systems will still be compromised, however.
#Rule Title: The system must require at least four characters be changed between the old and new passwords during a password change.
#Version: RHEL-06-000060

#Check Content: To check how many characters must differ during a password change, run the following command: 

#$ grep pam_cracklib /etc/pam.d/system-auth

#The "difok" parameter will indicate how many characters must differ. The DoD requires four characters differ during a password change. This would appear as "difok=8". 
#If difok is not found or not set to the required value, this is a finding.


#Fix Text: The pam_cracklib module's "difok" parameter controls requirements for usage of different characters during a password change. Add "difok=[NUM]" after pam_cracklib.so to require differing characters when changing passwords, substituting [NUM] appropriately. The DoD requirement is 4.

if grep pam_cracklib /etc/pam.d/system-auth|grep "difok=8"; then
echo "This machine is RHEL-06-000060 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000060 Compliant"
else
echo "This machine isn't RHEL-06-000060 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000060 Compliant"
sed -i '/^password    requisite/ s/$/ difok=8/' /etc/pam.d/system-auth
fi