#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38599
#Group Title: SRG-OS-000023
#Version: RHEL-06-000348
#Severity: medium
#Description: This setting will cause the system greeting banner to be used for FTP connections as well.
#Rule Title: The FTPS/FTP service on the system must be configured with the Department of Defense (DoD) login banner.
#Version: RHEL-06-000348

#Check Content: To verify this configuration, run the following command: 

#grep "banner_file" /etc/vsftpd/vsftpd.conf

#The output should show the value of "banner_file" is set to "/etc/issue", an example of which is shown below. 

# grep "banner_file" /etc/vsftpd/vsftpd.conf
#banner_file=/etc/issue


#If it does not, this is a finding.


#Fix Text: Edit the vsftpd configuration file, which resides at "/etc/vsftpd/vsftpd.conf" by default. Add or correct the following configuration options. 

#banner_file=/etc/issue

if grep "banner_file" /etc/vsftpd/vsftpd.conf; then
echo "This machine is RHEL-06-000348 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000348 Compliant"
else
echo "This machine isn't RHEL-06-000348 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000348 Compliant"
echo "banner_file=/etc/issue" >> /etc/vsftpd/vsftpd.conf
fi
