#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38669
#Group Title: SRG-OS-999999
#Version: RHEL-06-000287
#Severity: low
#Description: Local mail delivery is essential to some system maintenance and notification tasks.
#Rule Title: The postfix service must be enabled for mail delivery.
#Version: RHEL-06-000287

#Check Content: Run the following command to determine the current status of the "postfix" service:

# service postfix status

#If the service is enabled, it should return the following:

#postfix is running...

#If the service is not enabled, this is a finding.
#Fix Text: The Postfix mail transfer agent is used for local mail delivery within the system. The default configuration only listens for connections to the default SMTP port (port 25) on the loopback interface (127.0.0.1). It is recommended to leave this service enabled for local mail delivery. The "postfix" service can be enabled with the following command: 

# chkconfig postfix on
# service postfix start
if service postfix status|grep stop; then
echo "This machine isn't RHEL-06-000287 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000287 Compliant"
chkconfig postfix on
service postfix start
else
echo "This machine is RHEL-06-000287 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000287 Compliant"
fi
