#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38537
#Group Title: SRG-OS-999999
#Version: RHEL-06-000093
#Severity: low
#Description: Ignoring bogus ICMP error responses reduces log size, although some activity would not be logged.
#Rule Title: The system must ignore ICMPv4 bogus error responses.
#Version: RHEL-06-000093

#Check Content: The status of the "net.ipv4.icmp_ignore_bogus_error_responses" kernel parameter can be queried by running the following command: 

#$ sysctl net.ipv4.icmp_ignore_bogus_error_responses

#The output of the command should indicate a value of "1". If this value is not the default value, investigate how it could have been adjusted at runtime, and verify it is not set improperly in "/etc/sysctl.conf". 
#If the correct value is not returned, this is a finding.


#Fix Text: To set the runtime status of the "net.ipv4.icmp_ignore_bogus_error_responses" kernel parameter, run the following command: 

# sysctl -w net.ipv4.icmp_ignore_bogus_error_responses=1

#If this is not the system's default value, add the following line to "/etc/sysctl.conf": 

#net.ipv4.icmp_ignore_bogus_error_responses = 1
if grep ^net.ipv4.icmp_ignore_bogus_error_responses /etc/sysctl.conf|grep 1 ; then
echo "This machine is RHEL-06-000093 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000093 Compliant"
else
echo "This machine isn't RHEL-06-000093 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000093 Compliant"
if grep --silent ^net.ipv4.icmp_ignore_bogus_error_responses /etc/sysctl.conf ; then
	sed -i 's/^net.ipv4.icmp_ignore_bogus_error_responses.*/net.ipv4.icmp_ignore_bogus_error_responses = 1/g' /etc/sysctl.conf
else
	echo "" >> /etc/sysctl.conf
	echo "# Set net.ipv4.icmp_ignore_bogus_error_responses to 1 per security requirements" >> /etc/sysctl.conf
	echo "net.ipv4.icmp_ignore_bogus_error_responses = 1" >> /etc/sysctl.conf
fi
fi
