#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38615
#Group Title: SRG-OS-000023
#Version: RHEL-06-000240
#Severity: medium
#Description: The warning message reinforces policy awareness during the logon process and facilitates possible legal action against attackers. Alternatively, systems whose ownership should not be obvious should ensure usage of a banner that does not provide easy attribution.
#Rule Title: The SSH daemon must be configured with the Department of Defense (DoD) login banner.
#Version: RHEL-06-000240

#Check Content: To determine how the SSH daemon's "Banner" option is set, run the following command: 

# grep -i Banner /etc/ssh/sshd_config

#If a line indicating /etc/issue is returned, then the required value is set. 
#If the required value is not set, this is a finding.
#Fix Text: To enable the warning banner and ensure it is consistent across the system, add or correct the following line in "/etc/ssh/sshd_config": 
#Banner /etc/issue
#Another section contains information on how to create an appropriate system-wide warning banner.

if grep -i Banner /etc/ssh/sshd_config|grep -v '^#'|grep issue; then
echo "This machine is RHEL-06-000240 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000240 Compliant"
else
echo "This machine isn't RHEL-06-000240 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000240 Compliant"
echo "Banner /etc/issue" >> /etc/ssh/sshd_config
/etc/init.d/sshd restart
fi