#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38598
#Group Title: SRG-OS-000033
#Version: RHEL-06-000216
#Severity: high
#Description: The rexec service uses unencrypted network communications, which means that data from the login session, including passwords and all other information transmitted during the session, can be stolen by eavesdroppers on the network.
#Rule Title: The rexecd service must not be running.
#Version: RHEL-06-000216

#Check Content: To check that the "rexec" service is disabled in system boot configuration, run the following command: 

# chkconfig "rexec" --list

#Output should indicate the "rexec" service has either not been installed, or has been disabled at all runlevels, as shown in the example below: 

# chkconfig "rexec" --list
#"rexec" 0:off 1:off 2:off 3:off 4:off 5:off 6:off
#Run the following command to verify "rexec" is disabled through current runtime configuration: 
# service rexec status
#If the service is disabled the command will return the following output: 
#rexec is stopped
#If the service is running, this is a finding.
#Fix Text: The "rexec" service, which is available with the "rsh-server" package and runs as a service through xinetd, should be disabled. The "rexec" service can be disabled with the following command: 
# chkconfig rexec off
if chkconfig "rexec" --list|grep on; then
echo "This machine isn't RHEL-06-000216 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000216 Compliant"
chkconfig rexec off
/etc/init.d/rexec stop
else
echo "This machine is RHEL-06-000216 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000216 Compliant"
fi
