#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38477
#Group Title: SRG-OS-000075
#Version: RHEL-06-000051
#Severity: medium
#Description: Setting the minimum password age protects against users cycling back to a favorite password after satisfying the password reuse requirement.
#Rule Title: Users must not be able to change passwords more than once every 24 hours.
#Version: RHEL-06-000051

#Check Content: To check the minimum password age, run the command: 

#$ grep PASS_MIN_DAYS /etc/login.defs

#The DoD requirement is 1. 
#If it is not set to the required value, this is a finding.


#Fix Text: To specify password minimum age for new accounts, edit the file "/etc/login.defs" and add or correct the following line, replacing [DAYS] appropriately: 

#PASS_MIN_DAYS [DAYS]

#A value of 1 day is considered sufficient for many environments. The DoD requirement is 1.

if grep ^PASS_MIN_DAYS /etc/login.defs|grep -v "1"; then
echo "This machine isn't RHEL-06-000051 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000051 Compliant"
var_accounts_minimum_age_login_defs="1"
grep -q ^PASS_MIN_DAYS /etc/login.defs && \
  sed -i "s/PASS_MIN_DAYS.*/PASS_MIN_DAYS     $var_accounts_minimum_age_login_defs/g" /etc/login.defs
if ! [ $? -eq 0 ]; then
    echo "PASS_MIN_DAYS      $var_accounts_minimum_age_login_defs" >> /etc/login.defs
fi
else
echo "This machine is RHEL-06-000051 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000051 Compliant"
fi
