#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38692
#Group Title: SRG-OS-000003
#Version: RHEL-06-000334
#Severity: low
#Description: Disabling inactive accounts ensures that accounts which may not have been responsibly removed are not available to attackers who may have compromised their credentials.
#Rule Title: Accounts must be locked upon 35 days of inactivity.
#Version: RHEL-06-000334

#Check Content: To verify the "INACTIVE" setting, run the following command: 

#grep "INACTIVE" /etc/default/useradd

#The output should indicate the "INACTIVE" configuration option is set to an appropriate integer as shown in the example below: 
# grep "INACTIVE" /etc/default/useradd
#INACTIVE=35
#If it does not, this is a finding.
#Fix Text: To specify the number of days after a password expires (which signifies inactivity) until an account is permanently disabled, add or correct the following lines in "/etc/default/useradd", substituting "[NUM_DAYS]" appropriately: 

#INACTIVE=[NUM_DAYS]

#A value of 35 is recommended. If a password is currently on the verge of expiration, then 35 days remain until the account is automatically disabled. However, if the password will not expire for another 60 days, then 95 days could elapse until the account would be automatically disabled. See the "useradd" man page for more information. Determining the inactivity timeout must be done with careful consideration of the length of a "normal" period of inactivity for users in the particular environment. Setting the timeout too low incurs support costs and also has the potential to impact availability of the system to legitimate users.

if grep "INACTIVE" /etc/default/useradd|grep 35; then
echo "This machine is RHEL-06-000334 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000334 Compliant"
else
echo "This machine isn't RHEL-06-000334 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000334 Compliant"
sed -i 's@INACTIVE=.*@INACTIVE=35@g' /etc/default/useradd
fi
