#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38671
#Group Title: SRG-OS-999999
#Version: RHEL-06-000288
#Severity: medium
#Description: The sendmail software was not developed with security in mind and its design prevents it from being effectively contained by SELinux. Postfix should be used instead.
#Rule Title: The sendmail package must be removed.
#Version: RHEL-06-000288

#Check Content: Run the following command to determine if the "sendmail" package is installed: 
# rpm -q sendmail
#If the package is installed, this is a finding.
#Fix Text: Sendmail is not the default mail transfer agent and is not installed by default. The "sendmail" package can be removed with the following command: 
# yum erase sendmail

if rpm -q sendmail|grep "not installed"; then
echo "This machine is RHEL-06-000288 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000288 Compliant"
else
echo "This machine isn't RHEL-06-000288 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000288 Compliant"
yum erase sendmail -y
fi