#!/bin/bash
#Created by Matthew M. Conley / SimonTek

#Group ID: V-38620
#Group Title: SRG-OS-000056
#Version: RHEL-06-000247
#Severity: medium
#Description: Enabling the "ntpd" service ensures that the "ntpd" service will be running and that the system will synchronize its time to any servers specified. This is important whether the system is configured to be a client (and synchronize only its own clock) or it is also acting as an NTP server to other systems. Synchronizing time is essential for authentication services such as Kerberos, but it is also important for maintaining accurate logs and auditing possible security breaches.
#Rule Title: The system clock must be synchronized continuously, or at least daily.
#Version: RHEL-06-000247

#Check Content: Run the following command to determine the current status of the "ntpd" service: 

# service ntpd status

#If the service is enabled, it should return the following: 

#ntpd is running...


#If the service is not running, this is a finding.


#Fix Text: The "ntpd" service can be enabled with the following command: 

# chkconfig ntpd on
# service ntpd start
if service ntpd status|grep running; then
echo "This machine is RHEL-06-000247 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000247 Compliant"
else
echo "This machine isn't RHEL-06-000247 Compliant" >> /var/log/Stig
echo "This machine isn't RHEL-06-000247 Compliant"
/etc/init.d/ntpd on
chkconfig ntpd on
fi