#!/bin/bash
#Created by Matthew M. Conley / SimonTek
# Feb. 06, 2015

#Group ID (Vulid): V-54381
#Group Title: SRG-OS-999999
#Rule ID: SV-68627r1_rule
#Severity: CAT II
#Rule Version (STIG-ID): RHEL-06-000163
#Rule Title: The audit system must switch the system to single-user mode when available audit storage volume becomes dangerously low.

#Vulnerability Discussion: Administrators should be made aware of an inability to record audit records. If a separate partition or logical volume of adequate size is used, running low on space for audit records should never occur.

#Check Content: 
#Inspect "/etc/audit/auditd.conf" and locate the following line to determine if the system is configured to either suspend, switch to single-user mode, or halt when disk space has run low:

#admin_space_left_action single

#If the system is not configured to switch to single-user mode for corrective action, this is a finding.

#Fix Text: The "auditd" service can be configured to take an action when disk space is running low but prior to running out of space completely. Edit the file "/etc/audit/auditd.conf". Add or modify the following line, substituting [ACTION] appropriately:

#admin_space_left_action = [ACTION]

#Set this value to "single" to cause the system to switch to single-user mode for corrective action. Acceptable values also include "suspend" and "halt". For certain systems, the need for availability outweighs the need to log all actions, and a different setting should be determined. Details regarding all possible values for [ACTION] are described in the "auditd.conf" man page.  

#CCI: CCI-000366

if grep -i "admin_space_left_action"  /etc/audit/auditd.conf |grep -i single; then
echo "This machine is RHEL-06-000163 Compliant" >> /var/log/Stig
echo "This machine is RHEL-06-000163 Compliant"
else
echo "This machine isn't RHEL-06-000163 Compliant " >> /var/log/Stig
echo "This machine isn't RHEL-06-000163 Compliant "
grep -q admin_space_left_action /etc/audit/auditd.conf && \
  sed -i 's/admin_space_left_action.*/admin_space_left_action = SINGLE/g' /etc/audit/auditd.conf
if ! [ $? -eq 0 ]; then
    sed -i 's@#admin_space_left_action.*=.*@admin_space_left_action SINGLE@g' /etc/audit/auditd.conf
fi
fi
